/**
 * Copyright (c) 2026 Atharva Kusumbia
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the "app" directory of this source tree.
 */

/**
 * The two small images Windows' taskbar overlay needs (issue #1364).
 *
 * macOS takes a badge as a string - `app.setBadgeCount` renders it itself - but
 * `BrowserWindow.setOverlayIcon` takes a `NativeImage`, so a count on Windows is
 * a picture the app has to draw. This file draws it, and nothing else: no
 * Electron import, no file system, no state, so the shapes can be asserted pixel
 * by pixel in a unit test rather than looked at on a taskbar nobody runs in CI.
 *
 * **Why a bitmap rather than an asset.** The alternative is eleven PNGs under
 * `shared/` - one per count, one for the failed mark - regenerated by hand
 * whenever the accent changes and reviewed as binaries. A count is two glyphs on
 * a disc; drawing it costs less than shipping every answer, and it is the only
 * form a test can read back.
 *
 * `nativeImage.createFromBitmap` wants **BGRA**, premultiplied, row-major, which
 * is what {@link Bitmap.data} holds. It is drawn at twice the 16x16 the taskbar
 * asks for so the caller can hand it back at `scaleFactor: 2`.
 */

/** A raw image as `nativeImage.createFromBitmap` takes it. */
export interface Bitmap {
	/** BGRA, one byte per channel, `width * height * 4` long. */
	data: Uint8Array;
	width: number;
	height: number;
}

/** Logical size of a taskbar overlay, doubled so the drawing has room. */
export const OVERLAY_SIZE = 32;

/** The scale factor {@link OVERLAY_SIZE} is twice the logical size for. */
export const OVERLAY_SCALE = 2;

/**
 * The most a count says before it gives up on being exact.
 *
 * Ten would need three glyphs on a disc 32 pixels wide, and the number stops
 * being the point well before that: past nine the answer the user acts on is
 * "several", and the list behind the icon is where the exact figure lives.
 */
export const OVERLAY_MAX_COUNT = 9;

/** Colour channels as this file passes them around, 0-255. */
interface Rgb {
	r: number;
	g: number;
	b: number;
}

/**
 * The disc under a count.
 *
 * Deliberately not the accent: the accent is the user's and moves, and a count
 * that changed colour with the theme would read as a different kind of mark.
 * This is the same red the status tokens use for a destructive state, which is
 * what an unread pile on a taskbar button is closest to.
 */
const COUNT_FILL: Rgb = { r: 220, g: 38, b: 38 };

/** The failed mark's disc. One value, so the two marks cannot be confused. */
const FAILED_FILL: Rgb = { r: 185, g: 28, b: 28 };

/** Glyphs and the failed mark's slash, both drawn in white. */
const INK: Rgb = { r: 255, g: 255, b: 255 };

/**
 * A 3x5 bitmap font, one string of `#` and `.` per row.
 *
 * Three pixels wide is the narrowest a digit stays a digit, and at the 3x
 * scaling below that is nine device pixels per glyph - legible at the 16x16
 * the taskbar draws, which is the only size that matters here.
 */
const GLYPHS: Record<string, readonly string[]> = {
	"0": ["###", "#.#", "#.#", "#.#", "###"],
	"1": [".#.", "##.", ".#.", ".#.", "###"],
	"2": ["###", "..#", "###", "#..", "###"],
	"3": ["###", "..#", "###", "..#", "###"],
	"4": ["#.#", "#.#", "###", "..#", "..#"],
	"5": ["###", "#..", "###", "..#", "###"],
	"6": ["###", "#..", "###", "#.#", "###"],
	"7": ["###", "..#", "..#", "..#", "..#"],
	"8": ["###", "#.#", "###", "#.#", "###"],
	"9": ["###", "#.#", "###", "..#", "###"],
	"+": ["...", ".#.", "###", ".#.", "..."],
	"!": [".#.", ".#.", ".#.", "...", ".#."],
};

const GLYPH_WIDTH = 3;
const GLYPH_HEIGHT = 5;

/** Device pixels per font pixel. 3 puts a 3x5 glyph at 9x15 inside a 32px disc. */
const GLYPH_SCALE = 3;

/** Blank space between two glyphs, in device pixels. */
const GLYPH_GAP = 2;

function blank(size: number): Bitmap {
	return { data: new Uint8Array(size * size * 4), width: size, height: size };
}

/** Write one opaque pixel, ignoring anything outside the image. */
function plot(bitmap: Bitmap, x: number, y: number, colour: Rgb): void {
	if (x < 0 || y < 0 || x >= bitmap.width || y >= bitmap.height) return;
	const offset = (y * bitmap.width + x) * 4;
	bitmap.data[offset] = colour.b;
	bitmap.data[offset + 1] = colour.g;
	bitmap.data[offset + 2] = colour.r;
	bitmap.data[offset + 3] = 255;
}

/**
 * Fill a disc that touches all four edges.
 *
 * Hard-edged rather than antialiased: the coverage maths would be the one part
 * of this file a test could not read back as an exact value, and a 32-pixel disc
 * shown at 16 is resampled by the compositor anyway.
 */
function fillDisc(bitmap: Bitmap, colour: Rgb): void {
	const centre = (bitmap.width - 1) / 2;
	const radius = bitmap.width / 2;
	for (let y = 0; y < bitmap.height; y++) {
		for (let x = 0; x < bitmap.width; x++) {
			const dx = x - centre;
			const dy = y - centre;
			if (dx * dx + dy * dy <= radius * radius) plot(bitmap, x, y, colour);
		}
	}
}

/** Draw one glyph with its top-left at `originX`/`originY`, scaled up. */
function drawGlyph(bitmap: Bitmap, glyph: readonly string[], originX: number, originY: number): void {
	for (let row = 0; row < glyph.length; row++) {
		for (let column = 0; column < glyph[row].length; column++) {
			if (glyph[row][column] !== "#") continue;
			for (let dy = 0; dy < GLYPH_SCALE; dy++) {
				for (let dx = 0; dx < GLYPH_SCALE; dx++) {
					plot(
						bitmap,
						originX + column * GLYPH_SCALE + dx,
						originY + row * GLYPH_SCALE + dy,
						INK
					);
				}
			}
		}
	}
}

/** Centre a run of glyphs on the disc and draw them. */
function drawCentred(bitmap: Bitmap, text: string): void {
	const glyphs = [...text].map((character) => GLYPHS[character]).filter((glyph) => glyph);
	if (glyphs.length === 0) return;
	const scaledWidth = GLYPH_WIDTH * GLYPH_SCALE;
	const totalWidth = glyphs.length * scaledWidth + (glyphs.length - 1) * GLYPH_GAP;
	const originY = Math.round((bitmap.height - GLYPH_HEIGHT * GLYPH_SCALE) / 2);
	let originX = Math.round((bitmap.width - totalWidth) / 2);
	for (const glyph of glyphs) {
		drawGlyph(bitmap, glyph, originX, originY);
		originX += scaledWidth + GLYPH_GAP;
	}
}

/**
 * What a count reads as: itself up to {@link OVERLAY_MAX_COUNT}, then `9+`.
 *
 * Exported because it is also the overlay's accessibility description on
 * Windows, and the picture and the sentence a screen reader gets must not
 * disagree about how many there are.
 */
export function overlayCountText(count: number): string {
	if (!Number.isFinite(count)) return "";
	const whole = Math.floor(count);
	if (whole < 1) return "";
	return whole > OVERLAY_MAX_COUNT ? `${OVERLAY_MAX_COUNT}+` : `${whole}`;
}

/**
 * A disc carrying `count`, or `null` for a count with nothing to say.
 *
 * `null` rather than a blank image: the caller's way of taking the overlay off
 * is to pass Electron `null`, and returning an empty disc here would paint a
 * red dot meaning zero.
 */
export function countOverlayBitmap(count: number): Bitmap | null {
	const text = overlayCountText(count);
	if (!text) return null;
	const bitmap = blank(OVERLAY_SIZE);
	fillDisc(bitmap, COUNT_FILL);
	drawCentred(bitmap, text);
	return bitmap;
}

/**
 * The mark a failed run leaves: the same disc, carrying `!` rather than a
 * number, so the two states are one glance apart rather than one colour apart.
 */
export function failedOverlayBitmap(): Bitmap {
	const bitmap = blank(OVERLAY_SIZE);
	fillDisc(bitmap, FAILED_FILL);
	drawCentred(bitmap, "!");
	return bitmap;
}
