/**
 * @vitest-environment jsdom
 */
/**
 * Copyright (c) 2026 Atharva Kusumbia
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the "app" directory of this source tree.
 */

/**
 * The extensibility contract issue #1512 exists for: every kind the engine's
 * `GET /elements/kinds` serves must be *editable*, whether or not
 * `elementForms.ts` has ever heard of it. A kind with no bespoke override
 * falls through to the schema-driven `GenericElementForm`, so the app never
 * crashes on, or silently drops, a kind it has never seen.
 *
 * `engine/tests/fixtures/element-kinds.json` is not hand-maintained - it is
 * written by `elements_registry_test.cpp` on every engine test run, straight
 * off the live registry - so this reads it the same way the other
 * `*.conformance.test.ts` files read their engine fixtures. Held in
 * `ENGINE_READING_GUARDS` (`@/lib/routed-inputs.testkit`) so CI routes an edit
 * to the fixture back to this suite.
 *
 * This does **not** assert every kind needs a bespoke form - most legitimately
 * do not - only that the catalogue's current shape renders, for every kind,
 * without throwing and without silently producing an empty row.
 */

import { describe, it, expect, vi } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { render, fireEvent } from "@testing-library/react";
import { ENGINE_READING_GUARDS, fromRepoRoot } from "@/lib/routed-inputs.testkit";
import { ELEMENT_FORM_OVERRIDES } from "./elementForms";
import { ELEMENT_MODES, modeKeys } from "./element-modes";
import { ElementList } from "./index";
import { categoryIcon, effectiveCategory, kindIcon } from "./element-categories";
import type { ElementDef, ElementKindSchema } from "@/types";

// `script.pre` / `script.post` render the bespoke `ScriptElementForm`, whose
// `CodeEditor` (Monaco) does not run under jsdom, and whose snippets list
// reads a query this suite does not stand up a QueryClient for.
vi.mock("@/queries", async (importOriginal) => ({
	...(await importOriginal<typeof import("@/queries")>()),
	useScriptCompletionsQuery: () => ({ data: undefined, isPending: true, isError: false }),
}));
vi.mock("@/components/ui", async (importOriginal) => ({
	...(await importOriginal<typeof import("@/components/ui")>()),
	CodeEditor: () => <div data-testid="code-editor" />,
}));

/** Held in the testkit, so CI routes an edit to the fixture back to this suite. */
const [FIXTURE_PATH] = ENGINE_READING_GUARDS.elementKinds.paths.map(fromRepoRoot);

/**
 * Whether the fixture exists in this checkout. It is generated by the
 * engine's test suite (not hand-maintained), so an app-only session that has
 * not run `ctest` may not have it - this suite skips gracefully rather than
 * failing the whole run over an engine artifact it cannot produce, per this
 * file's own module comment and the orchestrating task's known gap.
 */
const fixtureExists = existsSync(FIXTURE_PATH);

describe.runIf(fixtureExists)("element-kinds conformance (fixture present)", () => {
	const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as ElementKindSchema[];

	it("scanned a non-empty fixture (guards the scan itself)", () => {
		expect(Array.isArray(fixture)).toBe(true);
		expect(fixture.length).toBeGreaterThan(0);
		for (const kind of fixture) {
			expect(typeof kind.kind).toBe("string");
			expect(kind.kind.length).toBeGreaterThan(0);
			expect(kind.configSchema).toBeTruthy();
		}
	});

	it("renders every catalogue kind, whether or not it has a bespoke form", () => {
		for (const kind of fixture) {
			const element: ElementDef = {
				id: `el_${kind.kind}`,
				kind: kind.kind,
				enabled: true,
				config: {},
			};

			expect(
				() =>
					render(
						<ElementList elements={[element]} onChange={() => {}} kinds={fixture} />
					),
				`rendering kind "${kind.kind}" threw`
			).not.toThrow();
		}
	});

	it("names, per kind, whether the app has a bespoke form or falls through to the generic one", () => {
		// Not an assertion that every kind *needs* one - most legitimately do
		// not - just a record of which side of the fallback each kind is on,
		// so a reviewer can see the split rather than infer it.
		const withBespoke = fixture
			.filter((k) => k.kind in ELEMENT_FORM_OVERRIDES)
			.map((k) => k.kind);
		const generic = fixture
			.filter((k) => !(k.kind in ELEMENT_FORM_OVERRIDES))
			.map((k) => k.kind);

		expect(withBespoke.length + generic.length).toBe(fixture.length);
		// Every `script.*` kind gets the bespoke Monaco form: `script.pre` /
		// `script.post` since #1512, `script.setup` / `script.teardown` since
		// #1499. The other five are the mutually-exclusive-strategy kinds
		// (`element-modes.ts`), whose schemas declare several alternative
		// strategies as independent optional siblings and which therefore need
		// a mode picker rather than every alternative's fields at once. This
		// fails loudly if the catalogue ever drops one or either map is edited
		// without this suite noticing.
		expect(withBespoke.sort()).toEqual([
			"assert.jsonpath",
			"assert.status",
			"control.throughput",
			"metric.record",
			"script.post",
			"script.pre",
			"script.setup",
			"script.teardown",
			"timer.think",
		]);
	});

	it("names, for every mode-picker kind, properties the live catalogue actually declares", () => {
		// `element-modes.ts` transcribes each kind's strategies from the
		// engine's own resolution order. A renamed or dropped property would
		// otherwise show as a mode whose fields are silently blank, or as a
		// strategy the picker can no longer reach - neither of which throws.
		// Mutation check: rename any id in `ELEMENT_MODES` and this reds
		// naming the kind and the key.
		for (const [kind, spec] of Object.entries(ELEMENT_MODES)) {
			const entry = fixture.find((k) => k.kind === kind);
			expect(entry, `the catalogue no longer serves "${kind}"`).toBeTruthy();

			const top = entry!.configSchema.properties ?? {};
			// Every one of these five relies on the schema refusing an unknown
			// key: it is what makes a leftover from a mode switch a save
			// failure rather than dead data the engine may still prefer.
			expect(
				entry!.configSchema.additionalProperties,
				`${kind} no longer refuses additional properties`
			).toBe(false);

			for (const name of [...(spec.leadNames ?? []), ...(spec.trailNames ?? [])]) {
				expect(Object.keys(top), `${kind} declares no "${name}"`).toContain(name);
			}

			const level = spec.path ? (top[spec.path]?.properties ?? {}) : top;
			expect(
				Object.keys(level).length,
				`${kind}'s mode level "${spec.path ?? "(top)"}" declares nothing`
			).toBeGreaterThan(0);
			for (const mode of spec.modes) {
				for (const key of modeKeys(mode)) {
					expect(Object.keys(level), `${kind} declares no "${key}"`).toContain(key);
				}
				if (mode.render === "nested") {
					expect(
						Object.keys(level[mode.id]?.properties ?? {}).length,
						`${kind}'s "${mode.id}" is rendered as a nested object but declares no children`
					).toBeGreaterThan(0);
				}
			}
		}
	});

	it("resolves every declared mode, in an order that is a permutation of them", () => {
		// The two orders are separate on purpose (the engine's priority, and
		// how the picker reads), which is exactly how one of them silently
		// loses a mode. Mutation check: drop an id from any `detectionOrder`
		// and this reds.
		for (const [kind, spec] of Object.entries(ELEMENT_MODES)) {
			expect([...spec.detectionOrder].sort(), `${kind}'s detection order`).toEqual(
				spec.modes.map((m) => m.id).sort()
			);
		}
	});

	it("renders a schema-driven field for a kind's own declared property, on the generic path", () => {
		// A kind the app has never special-cased is still editable: pick any
		// kind that falls through to `GenericElementForm` and assert its own
		// schema's property renders, expanded, under its schema-annotated
		// `title` (issue #1608) - not the raw property key, which is what the
		// generic form fell back to before #1607 gave every property one.
		// `inherit.disable` is deliberately excluded from the Add menu but not
		// from this check - the notice's Disable toggle still has to render
		// its form if the row is ever shown.
		const genericKind = fixture.find(
			(k) =>
				!(k.kind in ELEMENT_FORM_OVERRIDES) &&
				Object.keys(k.configSchema.properties ?? {}).length > 0
		);
		expect(genericKind, "no generic-form kind in the fixture declares a property").toBeTruthy();

		const element: ElementDef = {
			id: "el_generic",
			kind: genericKind!.kind,
			enabled: true,
			config: {},
		};
		const { getByRole, getByText } = render(
			<ElementList elements={[element]} onChange={() => {}} kinds={fixture} />
		);
		fireEvent.click(getByRole("button", { name: /^Expand /i }));

		const firstPropertyName = Object.keys(genericKind!.configSchema.properties ?? {})[0];
		const firstProperty = genericKind!.configSchema.properties![firstPropertyName];
		expect(getByText(firstProperty?.title ?? firstPropertyName)).toBeInTheDocument();
	});

	it("has a family icon for every category the fixture actually uses", () => {
		// The picker's category map (`element-categories.ts`) and the card's
		// family-icon map are kept in the same module so the two cannot name a
		// category differently; this is the icon half of that pairing, checked
		// against live categories the same way the picker's label map is
		// (`element-categories.conformance.test.tsx`). `inherit.disable` never
		// reaches a rendered card - `ElementList` filters it from the Add menu
		// by kind, and the inheritance notice's own disable toggle has no
		// family icon either - so it is excluded here the same way that
		// suite's own category check excludes it. Mutation check: delete one
		// entry from `CATEGORY_ICONS` and this reddens naming the category.
		const categories = new Set(
			fixture
				.filter((k) => k.kind !== "inherit.disable")
				.map((k) => effectiveCategory(k.category))
		);
		for (const category of categories) {
			expect(
				categoryIcon(category),
				`no family icon for category "${category}"`
			).toBeTruthy();
		}
	});

	it("resolves an icon for every catalogue kind, its own or the category's", () => {
		// `kindIcon` is what both `ElementRow`'s header and the Add-element
		// picker call - this is the guarantee that lets them: a kind with no
		// entry in `KIND_ICONS` still falls through to its (already-guarded)
		// category icon above, so neither ever renders blank. Mutation check:
		// delete one entry from `KIND_ICONS` and this still passes (the
		// fallback covers it) - the category test above is what catches a
		// missing *family* icon; this one is about the fallback firing at all.
		for (const kind of fixture) {
			if (kind.kind === "inherit.disable") continue;
			expect(kindIcon(kind), `no icon for kind "${kind.kind}"`).toBeTruthy();
		}
	});
});

describe.skipIf(fixtureExists)("element-kinds conformance (fixture missing)", () => {
	it("is skipped: engine/tests/fixtures/element-kinds.json was not found in this checkout", () => {
		// This fixture is generated by the engine's own test suite, not
		// hand-maintained - an app-only session has no way to produce it. Run
		// the engine test suite once (`ctest` under `engine/build`, per
		// `docs/engine/building.md`) to generate it, then re-run this file for
		// real coverage instead of this placeholder.
		expect(fixtureExists).toBe(false);
	});
});
