/**
 * @vitest-environment jsdom
 */
/**
 * Copyright (c) 2026 Atharva Kusumbia
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the "app" directory of this source tree.
 */

/**
 * The extensibility contract issue #1512 exists for: every kind the engine's
 * `GET /elements/kinds` serves must be *editable*, whether or not
 * `elementForms.ts` has ever heard of it. A kind with no bespoke override
 * falls through to the schema-driven `GenericElementForm`, so the app never
 * crashes on, or silently drops, a kind it has never seen.
 *
 * `engine/tests/fixtures/element-kinds.json` is not hand-maintained - it is
 * written by `elements_registry_test.cpp` on every engine test run, straight
 * off the live registry - so this reads it the same way the other
 * `*.conformance.test.ts` files read their engine fixtures. Held in
 * `ENGINE_READING_GUARDS` (`@/lib/routed-inputs.testkit`) so CI routes an edit
 * to the fixture back to this suite.
 *
 * This does **not** assert every kind needs a bespoke form - most legitimately
 * do not - only that the catalogue's current shape renders, for every kind,
 * without throwing and without silently producing an empty row.
 */

import { describe, it, expect, vi } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { render } from "@testing-library/react";
import { ENGINE_READING_GUARDS, fromRepoRoot } from "@/lib/routed-inputs.testkit";
import { ELEMENT_FORM_OVERRIDES } from "./elementForms";
import { ElementList } from "./index";
import type { ElementDef, ElementKindSchema } from "@/types";

// `script.pre` / `script.post` render the bespoke `ScriptElementForm`, whose
// `CodeEditor` (Monaco) does not run under jsdom, and whose snippets list
// reads a query this suite does not stand up a QueryClient for.
vi.mock("@/queries", async (importOriginal) => ({
	...(await importOriginal<typeof import("@/queries")>()),
	useScriptCompletionsQuery: () => ({ data: undefined, isPending: true, isError: false }),
}));
vi.mock("@/components/ui", async (importOriginal) => ({
	...(await importOriginal<typeof import("@/components/ui")>()),
	CodeEditor: () => <div data-testid="code-editor" />,
}));

/** Held in the testkit, so CI routes an edit to the fixture back to this suite. */
const [FIXTURE_PATH] = ENGINE_READING_GUARDS.elementKinds.paths.map(fromRepoRoot);

/**
 * Whether the fixture exists in this checkout. It is generated by the
 * engine's test suite (not hand-maintained), so an app-only session that has
 * not run `ctest` may not have it - this suite skips gracefully rather than
 * failing the whole run over an engine artifact it cannot produce, per this
 * file's own module comment and the orchestrating task's known gap.
 */
const fixtureExists = existsSync(FIXTURE_PATH);

describe.runIf(fixtureExists)("element-kinds conformance (fixture present)", () => {
	const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as ElementKindSchema[];

	it("scanned a non-empty fixture (guards the scan itself)", () => {
		expect(Array.isArray(fixture)).toBe(true);
		expect(fixture.length).toBeGreaterThan(0);
		for (const kind of fixture) {
			expect(typeof kind.kind).toBe("string");
			expect(kind.kind.length).toBeGreaterThan(0);
			expect(kind.configSchema).toBeTruthy();
		}
	});

	it("renders every catalogue kind, whether or not it has a bespoke form", () => {
		for (const kind of fixture) {
			const element: ElementDef = {
				id: `el_${kind.kind}`,
				kind: kind.kind,
				enabled: true,
				config: {},
			};

			expect(
				() =>
					render(
						<ElementList elements={[element]} onChange={() => {}} kinds={fixture} />
					),
				`rendering kind "${kind.kind}" threw`
			).not.toThrow();
		}
	});

	it("names, per kind, whether the app has a bespoke form or falls through to the generic one", () => {
		// Not an assertion that every kind *needs* one - most legitimately do
		// not - just a record of which side of the fallback each kind is on,
		// so a reviewer can see the split rather than infer it.
		const withBespoke = fixture
			.filter((k) => k.kind in ELEMENT_FORM_OVERRIDES)
			.map((k) => k.kind);
		const generic = fixture
			.filter((k) => !(k.kind in ELEMENT_FORM_OVERRIDES))
			.map((k) => k.kind);

		expect(withBespoke.length + generic.length).toBe(fixture.length);
		// `script.pre` / `script.post` are the one bespoke pair as of #1512 -
		// this fails loudly if the catalogue ever drops them or the overrides
		// map is edited without this suite noticing.
		expect(withBespoke.sort()).toEqual(["script.post", "script.pre"]);
	});

	it("renders a schema-driven field for a kind's own declared property, on the generic path", () => {
		// A kind the app has never special-cased is still editable: pick any
		// kind that falls through to `GenericElementForm` and assert its own
		// schema's property names actually reach the DOM. `inherit.disable`
		// is deliberately excluded from the Add menu but not from this check -
		// the notice's Disable toggle still has to render its form if the row
		// is ever shown.
		const genericKind = fixture.find(
			(k) =>
				!(k.kind in ELEMENT_FORM_OVERRIDES) &&
				Object.keys(k.configSchema.properties ?? {}).length > 0
		);
		expect(genericKind, "no generic-form kind in the fixture declares a property").toBeTruthy();

		const element: ElementDef = {
			id: "el_generic",
			kind: genericKind!.kind,
			enabled: true,
			config: {},
		};
		const { getByText } = render(
			<ElementList elements={[element]} onChange={() => {}} kinds={fixture} />
		);

		const firstProperty = Object.keys(genericKind!.configSchema.properties ?? {})[0];
		expect(getByText(firstProperty)).toBeInTheDocument();
	});
});

describe.skipIf(fixtureExists)("element-kinds conformance (fixture missing)", () => {
	it("is skipped: engine/tests/fixtures/element-kinds.json was not found in this checkout", () => {
		// This fixture is generated by the engine's own test suite, not
		// hand-maintained - an app-only session has no way to produce it. Run
		// the engine test suite once (`ctest` under `engine/build`, per
		// `docs/engine/building.md`) to generate it, then re-run this file for
		// real coverage instead of this placeholder.
		expect(fixtureExists).toBe(false);
	});
});
