/**
 * @file tests/import_parse_test.cpp
 * @brief Parsing an import document engine-side (issue #877).
 *
 * **The fixture leads, and it is a migration record before it is a test.**
 * `fixtures/import-conformance.json` was generated by running the renderer's
 * own parsers - `postman.ts`, `insomnia-v4.ts`, `postman-environment.ts`,
 * `openapi-v3.ts`, `openapi-v2.ts` and the factory that dispatched between them
 * - over each document at 8e1c566, the last commit that had them. Every
 * `expected` in it is therefore what the app produced for those bytes before
 * the parse moved here, which is what makes "the import is unchanged by the
 * move" a claim a test can fail rather than a promise in a PR body. Those
 * parsers are deleted in the same commit, so this is the engine's own table
 * from now on - the same shape `operation-shape-conformance.json` took when its
 * renderer half went (#761).
 *
 * Two normalisations before the comparison, both of them differences the
 * *renderer* could not avoid rather than answers this side chose:
 *
 * - **`meta.skipped` is compared as counts per kind.** The renderer emitted
 *   first-seen order out of a `Map`; `ImportTally` emits a fixed order. A
 *   counter list is a set of counters and nothing reads its order.
 * - **A request's `examples` are compared sorted by status.** A JavaScript
 *   object orders integer-like keys numerically ahead of the rest, so a
 *   document writing `responses: {404, 200}` reached the renderer as
 *   `200, 404`; the engine's reader keeps document order, which is the promise
 *   `read_document` makes and the one a stored `order` should have had all
 *   along. Which responses there are, and what each carries, must still agree
 *   exactly.
 *
 * The cases below the fixture are the rules a fixture cannot state: what the
 * route refuses, and what a document no format claims is answered with.
 */

#include <gtest/gtest.h>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <string>

#include <nlohmann/json.hpp>

#include "temp_database.hpp"
#include "vayu/core/import_document.hpp"
#include "vayu/db/database.hpp"

namespace vayu::http::routes {
std::pair<int, nlohmann::json>
import_parse_response (vayu::db::Database& db, const nlohmann::json& body);
std::pair<int, nlohmann::json>
import_document_response (vayu::db::Database& db, const nlohmann::json& body);
std::pair<int, nlohmann::json>
import_response (vayu::db::Database& db, const nlohmann::json& body);
} // namespace vayu::http::routes

namespace {

using nlohmann::json;
using vayu::core::ImportOptions;
using vayu::core::ImportParse;
using vayu::core::ImportSource;
using vayu::core::parse_import;

json read_fixture () {
    const std::filesystem::path path =
    std::filesystem::path (__FILE__).parent_path () / "fixtures" / "import-conformance.json";
    std::ifstream file (path);
    EXPECT_TRUE (file.is_open ()) << "missing fixture: " << path;
    json fixture;
    file >> fixture;
    return fixture;
}

/// `meta.skipped` as `{kind: count}` - see the file comment.
json skip_counts (const json& skipped) {
    json counts = json::object ();
    for (const json& entry : skipped) {
        const std::string kind = entry.at ("kind").get<std::string> ();
        counts[kind]           = counts.contains (kind) ?
                  counts[kind].get<int> () + entry.at ("count").get<int> () :
                  entry.at ("count").get<int> ();
    }
    return counts;
}

void sort_examples (json& collections) {
    for (json& collection : collections) {
        for (json& request : collection.at ("requests")) {
            if (!request.contains ("examples")) {
                continue;
            }
            json& examples = request.at ("examples");
            std::stable_sort (examples.begin (), examples.end (),
            [] (const json& a, const json& b) {
                return a.at ("status").get<int> () < b.at ("status").get<int> ();
            });
        }
        sort_examples (collection.at ("children"));
    }
}

/// The comparable form of a result: plain `json` (whose objects compare by key,
/// not by insertion order) with the two normalisations above applied.
json comparable (const nlohmann::ordered_json& result) {
    json out               = json::parse (result.dump ());
    out["meta"]["skipped"] = skip_counts (out.at ("meta").at ("skipped"));
    sort_examples (out.at ("collections"));
    return out;
}

ImportOptions options_of (const json& declared) {
    ImportOptions options;
    options.import_environments = declared.at ("importEnvironments").get<bool> ();
    options.import_scripts = declared.at ("importScripts").get<bool> ();
    return options;
}

ImportSource source_of (const json& entry) {
    ImportSource source;
    if (const auto declared = entry.find ("source"); declared != entry.end ()) {
        if (const auto found = declared->find ("fileName"); found != declared->end ()) {
            source.file_name = found->get<std::string> ();
        }
        if (const auto found = declared->find ("sourceUrl"); found != declared->end ()) {
            source.source_url = found->get<std::string> ();
        }
        if (const auto found = declared->find ("unresolvedRefs");
        found != declared->end ()) {
            source.unresolved_refs = found->get<int> ();
        }
    }
    return source;
}

TEST (ImportConformance, MatchesTheParsersItReplaced) {
    const json fixture = read_fixture ();
    ASSERT_FALSE (fixture.at ("cases").empty ())
    << "an empty corpus proves nothing";

    for (const json& entry : fixture.at ("cases")) {
        const std::string name = entry.at ("name").get<std::string> ();
        const ImportParse parsed =
        parse_import (entry.at ("document").get<std::string> (),
        options_of (entry.at ("options")), source_of (entry));
        ASSERT_TRUE (parsed.ok ()) << name << ": " << parsed.error;

        const json expected =
        comparable (nlohmann::ordered_json::parse (entry.at ("expected").dump ()));
        EXPECT_EQ (comparable (parsed.result), expected) << "case: " << name;
    }
}

/**
 * The other half of the fixture: the `POST /import/apply` payload each result
 * flattens to (issue #877).
 *
 * `POST /import` builds it here and the app builds it in `orchestrator.ts`,
 * because the app applies a *previewed and filtered* result and this route
 * applies a document. Two implementations of one mapping is the repo's
 * hand-rolled-copy defect in the one place a missing field is silent - a
 * request that imported without its examples looks exactly like a document
 * that documented none - so both are pinned to the same `payload`, this side
 * here and the renderer's in `orchestrator.payload-conformance.test.ts`.
 */
TEST (ImportApplyPayload, MatchesWhatTheOrchestratorFlattens) {
    const json fixture = read_fixture ();
    for (const json& entry : fixture.at ("cases")) {
        const std::string name = entry.at ("name").get<std::string> ();
        ASSERT_TRUE (entry.contains ("payload")) << name << ": no payload recorded";
        const nlohmann::ordered_json result =
        nlohmann::ordered_json::parse (entry.at ("expected").dump ());
        EXPECT_EQ (json::parse (vayu::core::import_apply_payload (result).dump ()),
        entry.at ("payload"))
        << "case: " << name;
    }
}

TEST (ImportParse, RefusesADocumentNoFormatClaims) {
    const ImportParse parsed = parse_import (R"({"hello":"world"})", {}, {});
    EXPECT_FALSE (parsed.ok ());
    EXPECT_TRUE (parsed.unrecognised);
    EXPECT_EQ (parsed.error, "Unrecognised format");
}

TEST (ImportParse, RefusesBytesThatAreNeitherJsonNorYaml) {
    // Told apart from "unrecognised" deliberately: one says Vayu does not read
    // this kind of file, the other that this file is broken.
    const ImportParse parsed = parse_import ("{ unclosed: [1, 2", {}, {});
    EXPECT_FALSE (parsed.ok ());
    EXPECT_FALSE (parsed.unrecognised);
    EXPECT_NE (parsed.error.find ("Could not read the document"), std::string::npos);
}

TEST (ImportParse, NamesTheFieldOfAMalformedInsomniaExport) {
    const ImportParse parsed = parse_import (
    R"({"_type":"export","__export_format":4,"resources":"nope"})", {}, {});
    EXPECT_FALSE (parsed.ok ());
    EXPECT_FALSE (parsed.unrecognised);
    EXPECT_EQ (parsed.error, "Malformed Insomnia export: `resources` must be an array");
}

TEST (ImportParse, StepsOverACycleInAnInsomniaFolderTree) {
    // Insomnia cannot emit one (`parentId` is a single edge), but a mangled file
    // can, and an unguarded walk answers that by running out of stack.
    const ImportParse parsed = parse_import (R"({"_type":"export","__export_format":4,"resources":[
        {"_id":"wrk","_type":"workspace","name":"W"},
        {"_id":"a","_type":"request_group","parentId":"wrk","name":"A"},
        {"_id":"wrk2","_type":"request_group","parentId":"a","name":"B"}]})",
    {}, {});
    ASSERT_TRUE (parsed.ok ()) << parsed.error;
    EXPECT_EQ (parsed.result.at ("meta").at ("folderCount"), 2);
}

TEST (ImportParse, GatingTheOptionsChangesWhatTheCountsPromise) {
    const std::string document = R"({"_postman_variable_scope":"environment","name":"Prod",
        "values":[{"key":"host","value":"x"}]})";
    ImportOptions off;
    off.import_environments = false;

    const ImportParse on    = parse_import (document, {}, {});
    const ImportParse gated = parse_import (document, off, {});
    ASSERT_TRUE (on.ok ());
    ASSERT_TRUE (gated.ok ());
    EXPECT_EQ (on.result.at ("meta").at ("environmentCount"), 1);
    // Gated at parse time rather than stripped afterwards, so the preview counts
    // what will actually be created.
    EXPECT_EQ (gated.result.at ("meta").at ("environmentCount"), 0);
    EXPECT_TRUE (gated.result.at ("environments").empty ());
}

/**
 * A relative `servers[0].url` against the URL the document was fetched from -
 * `new URL(reference, base)`, which the engine has to answer itself.
 *
 * The corpus covers the ordinary case (`../v2`); these are the shapes a
 * segment-wise resolver gets wrong, and each one changes the host a request
 * would reach. A base with no scheme is `new URL`'s `TypeError`, which the
 * caller reports as an unresolved base rather than guessing.
 */
TEST (ImportParse, ResolvesARelativeServerUrlAgainstTheDocumentsOwn) {
    const auto base_url = [] (const std::string& server, const std::string& source) {
        ImportSource from;
        from.source_url          = source;
        const ImportParse parsed = parse_import (
        R"({"openapi":"3.0.0","info":{"title":"T"},"servers":[{"url":")" + server + R"("}],"paths":{}})",
        {}, from);
        EXPECT_TRUE (parsed.ok ()) << parsed.error;
        const json variables =
        json::parse (parsed.result.at ("collections")[0].at ("variables").dump ());
        return variables.contains ("baseUrl") ?
        variables.at ("baseUrl").at ("value").get<std::string> () :
        std::string ();
    };

    const std::string source = "https://api.example.com/specs/v1/openapi.yaml";
    EXPECT_EQ (base_url ("/v3", source), "https://api.example.com/v3");
    EXPECT_EQ (base_url ("api", source), "https://api.example.com/specs/v1/api");
    EXPECT_EQ (base_url ("../../v2", source), "https://api.example.com/v2");
    // The last segment being `..` keeps the trailing slash - `/specs/v1/..` is
    // `/specs/`, and dropping it would name a different resource.
    EXPECT_EQ (base_url ("..", source), "https://api.example.com/specs/");
    EXPECT_EQ (base_url ("//other.example.com/v1", source), "https://other.example.com/v1");
    // Already absolute: nothing to resolve against.
    EXPECT_EQ (base_url ("https://other.example.com/v1", source), "https://other.example.com/v1");
    // A base that is not absolute resolves nothing; the URL imports as written.
    EXPECT_EQ (base_url ("/v3", "not-a-url"), "/v3");
}

class ImportParseRoute : public ::testing::Test {
    protected:
    static constexpr const char* DB_PATH = "test_import_parse_route.db";

    void SetUp () override {
        cleanup ();
        db_ = std::make_unique<vayu::db::Database> (DB_PATH);
        db_->init ();
    }
    void TearDown () override {
        db_.reset ();
        cleanup ();
    }
    static void cleanup () {
        vayu::tests::remove_database_files (DB_PATH);
    }

    std::unique_ptr<vayu::db::Database> db_;
};

TEST_F (ImportParseRoute, AnswersTheWholeImportResult) {
    auto [status, body] = vayu::http::routes::import_parse_response (*db_,
    json{ { "content", R"({"info":{"name":"C","schema":"v2.1.0"},"item":[]})" } });
    ASSERT_EQ (status, 200) << body.dump ();
    EXPECT_EQ (body.at ("meta").at ("format"), "Postman Collection v2.1");
    EXPECT_TRUE (body.contains ("collections"));
    EXPECT_TRUE (body.contains ("environments"));
    EXPECT_TRUE (body.contains ("globals"));
}

TEST_F (ImportParseRoute, RefusesADocumentOverTheStoredCap) {
    // Reuses `maxSpecDocumentBytes` rather than growing a second knob: the whole
    // document is read into memory whatever format claims it, and an OpenAPI
    // import stores exactly these bytes.
    auto entry = db_->get_config_entry ("maxSpecDocumentBytes");
    ASSERT_TRUE (entry.has_value ());
    entry->value = "64";
    db_->save_config_entry (*entry);
    auto [status, body] = vayu::http::routes::import_parse_response (
    *db_, json{ { "content", std::string (200, 'x') } });
    EXPECT_EQ (status, 413);
    EXPECT_NE (body.at ("error").at ("message").get<std::string> ().find (
               "maxSpecDocumentBytes"),
    std::string::npos);
}

TEST_F (ImportParseRoute, PassesTheUnrecognisedSentenceThrough) {
    auto [status, body] = vayu::http::routes::import_parse_response (
    *db_, json{ { "content", R"({"a":1})" } });
    EXPECT_EQ (status, 400);
    EXPECT_EQ (body.at ("error").at ("message"), "Unrecognised format");
}

TEST_F (ImportParseRoute, RefusesAnEmptyOrAbsentDocument) {
    EXPECT_EQ (vayu::http::routes::import_parse_response (*db_, json::object ()).first, 400);
    EXPECT_EQ (
    vayu::http::routes::import_parse_response (*db_, json{ { "content", "" } }).first, 400);
    EXPECT_EQ (vayu::http::routes::import_parse_response (
               *db_, json{ { "content", "{}" }, { "importScripts", "yes" } })
               .first,
    400);
}

TEST_F (ImportParseRoute, ReadsADocumentIntoADomForTheRefBundler) {
    auto [status, body] = vayu::http::routes::import_document_response (
    *db_, json{ { "content", "openapi: 3.0.0\npaths:\n  /a:\n    get: {}\n" } });
    ASSERT_EQ (status, 200) << body.dump ();
    EXPECT_EQ (body.at ("document").at ("openapi"), "3.0.0");
    // Order is the document's, which is the whole reason a YAML reader in the
    // renderer could not answer this question the same way.
    EXPECT_TRUE (body.at ("document").at ("paths").contains ("/a"));
}

TEST_F (ImportParseRoute, PersistsTheWholeTreeInOneCall) {
    auto [status, body] = vayu::http::routes::import_response (
    *db_, json{ { "content", R"({"info":{"name":"CB","schema":"v2.1.0"},"item":[
        {"name":"Ping","request":{"method":"GET","url":"https://x/ping"}}]})" } });
    ASSERT_EQ (status, 200) << body.dump ();
    EXPECT_EQ (body.at ("collections"), 1);
    EXPECT_EQ (body.at ("requests"), 1);
    EXPECT_EQ (body.at ("meta").at ("format"), "Postman Collection v2.1");
    // Every temp id the flattening minted comes back mapped to a real one.
    EXPECT_TRUE (body.at ("idMap").contains ("c1"));
    EXPECT_TRUE (body.at ("idMap").contains ("r1"));
    EXPECT_EQ (db_->get_collections ().size (), 1U);
}

/**
 * The globals half, which is the one write outside the transaction.
 *
 * It is also the one that can vanish silently: `Globals` is a singleton
 * addressed by a fixed id, so a row saved without it is a row `get_globals`
 * never finds - the import would report four variables written and the scope
 * would still be empty. Reverting the `row.id` line reddens the first
 * assertion.
 */
TEST_F (ImportParseRoute, WritesAGlobalsExportIntoTheGlobalScopeAndMergesASecond) {
    const auto import_globals = [this] (const std::string& values) {
        auto [status, body] = vayu::http::routes::import_response (*db_,
        json{ { "content",
        R"({"_postman_variable_scope":"globals","values":)" + values + "}" } });
        EXPECT_EQ (status, 200) << body.dump ();
    };
    const auto stored = [this] {
        const auto row = db_->get_globals ();
        return row ? json::parse (row->variables) : json::object ();
    };

    import_globals (R"([{"key":"host","value":"a"},{"key":"token","value":"b"}])");
    EXPECT_EQ (stored (),
    (json{ { "host", { { "value", "a" }, { "enabled", true } } },
    { "token", { { "value", "b" }, { "enabled", true } } } }));

    // A second import **merges**: the engine has no merge verb, and writing the
    // import's globals alone would delete every global the user already had.
    // The imported value wins a collision - the caller asked for this file's
    // variables, and skipping them would be the silent no-op.
    import_globals (R"([{"key":"host","value":"z"},{"key":"extra","value":"c"}])");
    EXPECT_EQ (stored (),
    (json{ { "host", { { "value", "z" }, { "enabled", true } } },
    { "token", { { "value", "b" }, { "enabled", true } } },
    { "extra", { { "value", "c" }, { "enabled", true } } } }));
}

TEST_F (ImportParseRoute, RefusesBytesThatAreNotADocument) {
    auto [status, body] = vayu::http::routes::import_document_response (
    *db_, json{ { "content", "{ unclosed: [1, 2" } });
    EXPECT_EQ (status, 400);
    EXPECT_NE (body.at ("error").at ("message").get<std::string> ().find (
               "Invalid 'content'"),
    std::string::npos);
}

} // namespace
