#pragma once

/*
 * Copyright (c) 2026 Atharva Kusumbia
 *
 * This source code is licensed under the AGPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * @file core/import_document.hpp
 * @brief Reading an import document engine-side (issue #877) - the last parser
 *        to move, and the one that makes #853's "exactly one parser has an
 *        opinion" true.
 *
 * Everything else about a document had already moved: what a stored OpenAPI
 * document *declares* (#853), the response schemas it carries (#860), the
 * requests an import of it *would* build (#865), what a re-fetch would change
 * (#854). What stayed in the renderer was the import itself - the four format
 * parsers under `app/src/services/importers/` - and with it the fact that an
 * agent over MCP could bind, diff, sync and export a spec but could not import
 * a document at all. This is that parse, for all four formats:
 *
 * - **OpenAPI 2.0 / 3.x**, which do not get a second reader here: the requests
 *   come from `core::import_drafts_of` - the #865 builder over the #853 reader
 *   - and this file composes the collection, the folders and the counts around
 *   them.
 * - **Postman Collection v2.0 / v2.1**, **Postman environment / globals** and
 *   **Insomnia Export v4**, ported from the renderer's parsers to nlohmann.
 *   All three are JSON-only formats, so no YAML question arrives with them.
 *
 * **The output is `ImportResult` verbatim**, the same tree the renderer's
 * `parseImport` returned: collections with their requests, environments,
 * globals, and the `meta` the import preview reads. It deliberately stops
 * there. Temp ids (`assign-ids.ts`) and the flattening into `POST /import/apply`
 * (`orchestrator.ts`) stay renderer-side - they are about a *write*, not about
 * what a document says - and so does detection of which file the user picked
 * and the preview that shows it.
 *
 * **Held to the renderer's answers, not to its code.** The rules below read
 * like JavaScript in C++ clothing because that is the point: `??` falls through
 * `null` and not `false`, `if (row.key)` is truthiness, `String(5)` is a name.
 * `tests/fixtures/import-conformance.json` was generated by those parsers before
 * they were deleted, so every expectation in it is what the app actually
 * produced - the migration is a test rather than a promise.
 */

#include <nlohmann/json.hpp>
#include <string>

namespace vayu::core {

/// `fileBaseName(path)`: the last segment of @p path, for either platform's
/// separator - the path comes from whoever's machine produced the export.
[[nodiscard]] std::string file_base_name (const std::string& path);

/**
 * `importedFilePart(entry, src, contentType?)`: @p entry (already carrying a
 * `key`/`value`/`enabled`/`description`) turned into a multipart part that
 * uploads a file at @p src.
 *
 * @p src is kept exactly as the source wrote it and a row that has one is
 * marked **unresolved**, because it names a file on the exporting machine, not
 * one Vayu can read. Shared by every importer that has to turn a
 * source-machine file reference into a formdata part - Postman/Insomnia
 * (`import_document.cpp`) and a JMeter `HTTPsampler.Files` upload
 * (`jmeter_import.cpp`, issue #1657) - so the row shape cannot drift between
 * them.
 */
[[nodiscard]] nlohmann::ordered_json imported_file_part (nlohmann::ordered_json entry,
const std::string& src,
const std::string* content_type);

/**
 * A Postman raw body as the Vayu body the importer stores: `{mode, content}`,
 * where a declared `options.raw.language` that is a Vayu mode (`json`, `text`,
 * `xml`) is that mode and anything else - no language at all included - is
 * sniffed (JSON that parses is `json`, the rest `text`). A sniffed body also
 * keeps what was declared as `rawLanguage`, `""` for none, so the exporter
 * can write the body's `options` back as Postman had them.
 *
 * Shared with the exporter (`postman_export.cpp`), which writes a stored
 * `rawLanguage` back only while this mapping still gives the stored mode, so
 * a body edited into another mode since is written the way its mode says.
 */
[[nodiscard]] nlohmann::ordered_json
postman_raw_body (const std::string& content, const std::string* language);

/**
 * A Postman `auth` object (`{type, <type>: attributes}`, either schema
 * version) as the Vayu auth the importer stores for a request, without the
 * `postman` source it may add. The Postman exporter calls it to tell whether
 * a stored auth's `postman` source still describes that auth - mapping it
 * again gives the auth, so the user has not changed it since.
 */
[[nodiscard]] nlohmann::ordered_json postman_auth_mapping (
const nlohmann::ordered_json& auth);

/**
 * Whether @p auth (a stored Vayu auth) carries a `postman` source that still
 * describes it: mapping the source through `postman_auth_mapping` gives
 * @p auth without the source. The exporter writes such a source verbatim.
 */
[[nodiscard]] bool postman_source_stands (const nlohmann::json& auth);

/**
 * @p stored (an `auth` column's text) without its `postman` source once the
 * source no longer describes it. Every auth write goes through this
 * (`routes/requests.cpp`, `routes/collections.cpp`): a source kept past an
 * edit would hold the credential the edit replaced, and every read of the
 * row (`GET /requests`, the MCP tools) would return it.
 */
[[nodiscard]] std::string without_stale_postman_source (std::string stored);

/// The two toggles the import dialog offers, applied at parse time so the
/// preview counts what will actually be created.
struct ImportOptions {
    bool import_environments = true;
    /// Off makes every parser emit empty scripts rather than the caller
    /// stripping them afterwards - a count that disagreed with the tree is the
    /// thing this being a parse-time rule prevents.
    bool import_scripts = true;
};

/**
 * Where the bytes came from, for the facts no parser can read out of them.
 *
 * `file_name` is display only. `source_url` is persisted as a spec document's
 * `sourceUrl` *and* is what a relative `servers[0].url` resolves against, which
 * is why it reaches the parse rather than being stamped on afterwards (#719).
 * `unresolved_refs` is the bundling pass's count (#649): bundling happens
 * before this, so no parser can know it, and a loss the preview never names is
 * the defect bundling exists to fix.
 */
struct ImportSource {
    std::string file_name;
    std::string source_url;
    int unresolved_refs = 0;
};

/// A parsed import, or the caller-facing sentence saying why these bytes are
/// not one. The sentence is what a `400` carries, so it names the failure -
/// a caller that cannot act on the answer will send the same bytes again.
struct ImportParse {
    /// The `ImportResult`. `null` when @ref error is set.
    nlohmann::ordered_json result;
    /// Empty on success.
    std::string error;
    /**
     * Whether the failure was "no parser claims this file" as opposed to a
     * document that claimed a format and was broken. The renderer told those
     * apart (`UnrecognisedFormatError` versus a parse error) and the import
     * dialog says different things about them, so the distinction survives the
     * move rather than collapsing into one 400.
     */
    bool unrecognised = false;

    [[nodiscard]] bool ok () const {
        return error.empty ();
    }
};

/**
 * @brief Parse @p text as whichever import format claims it.
 *
 * Detection runs in `factory.ts`'s order - Postman v2.1, v2.0, environment,
 * Insomnia v4, OpenAPI 3.x, OpenAPI 2.0 - so a document carrying two formats'
 * keys is claimed by the same one on both sides. The bytes are read once (JSON,
 * then YAML) through `core::read_document`, which is the *only* reader in the
 * engine and now the only one anywhere.
 *
 * @param text  The document, verbatim. An OpenAPI import stores exactly these
 *              bytes as its `SpecDraft.content`, because the engine hashes what
 *              it stores and a re-serialization would make every YAML spec
 *              drift on its first sync.
 */
[[nodiscard]] ImportParse parse_import (const std::string& text,
const ImportOptions& options,
const ImportSource& source);

/**
 * A Postman row array (`header[]`, `query[]`) as the importer stores it: the
 * `key`/`value`/`enabled`/`description` rows `map_key_values` builds. The
 * Postman export compares a stored saved response's `header[]` through this
 * against the example's `headers` column, so "still what was imported" is
 * decided by the same reading the import made.
 */
[[nodiscard]] nlohmann::ordered_json postman_header_rows (const nlohmann::ordered_json& rows);

/**
 * @brief An `ImportResult` as the `POST /import/apply` payload that persists it.
 *
 * The other half of what the renderer kept when the parse moved: `assign-ids.ts`
 * stamps every draft with an opaque temp id, and `orchestrator.ts` flattens the
 * tree into the four sections the apply takes. Both stayed there because they
 * are about a *write* rather than about a document - and then an agent asked to
 * import a document over MCP, where there is no renderer to run them.
 *
 * So `POST /import` - parse and persist in one call, which is what an agent
 * wants - flattens here. The renderer still flattens in `orchestrator.ts`,
 * because it applies a *previewed and filtered* result: the user has ticked
 * which files of a batch to import and toggled two options since the parse, and
 * a route that re-parsed would be answering about a different set. Two
 * implementations of one mapping is the repo's hand-rolled-copy defect waiting
 * to happen, in the one place a missing field is silent - a request that
 * imported without its examples looks exactly like a document that documented
 * none - so they are pinned to each other: `import_parse_test.cpp` and
 * the app's `orchestrator.payload-conformance.test.ts` build the payload for
 * the same fixtures and must agree.
 *
 * Temp ids are `c1` / `r1` / `e1` / `s1`, in the walk's order, exactly as
 * `assign-ids.ts` mints them: they are opaque and per-call, and a readable one
 * makes a rejected payload name an item a human can find.
 *
 * `ImportResult.globals` is deliberately **not** in the payload. Globals are an
 * engine singleton behind `POST /globals`, not a tree item with a temp id, so
 * they stay a separate write - see `POST /import`, which does it last and for
 * the reason the orchestrator does.
 */
[[nodiscard]] nlohmann::ordered_json import_apply_payload (
const nlohmann::ordered_json& result);

} // namespace vayu::core
