#pragma once

/*
 * Copyright (c) 2026 Atharva Kusumbia
 *
 * This source code is licensed under the AGPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 */

/**
 * @file core/schema_error_text.hpp
 * @brief One valijson constraint failure, translated into plain English.
 *
 * `valijson::ValidationResults::Error::description` is generated by the
 * validator itself, in JSON-Schema-keyword vocabulary a wire caller
 * understands and a person reading a toast or a Response Viewer panel does
 * not: "Value type not permitted by 'type' constraint.", "Missing required
 * property 'x'.". Two callers show this verbatim to a person -
 * `elements/registry.cpp`'s element-config validation and
 * `schema_validation.cpp`'s response-body validation - so the translation
 * lives once, here, rather than twice.
 */

#include <nlohmann/json_fwd.hpp>

#include <string>

namespace vayu::core {

/**
 * valijson's own wording for one schema-constraint failure, translated into
 * plain English for the constraints this engine's own callers actually
 * trigger - `type`, `required`, `additionalProperties`, `minimum`/`maximum`,
 * `minLength`/`maxLength`, `enum`, `pattern`. Reads the failing property's
 * own declared `"title"` (and `"description"` for a `pattern` failure, which
 * names no bound of its own to restate) off @p schema at the JSON Pointer
 * the error names, and the schema's own declared bound or enum list, rather
 * than re-parsing them out of valijson's text - so the message stays correct
 * even if valijson's own phrasing changes between versions, and reads well
 * whether @p schema is one of this engine's own element config schemas
 * (which #1607 guarantees a title on every property) or an imported
 * document's response schema (which may declare none, in which case the
 * property's own JSON key is shown instead).
 *
 * @p schema is walked only through `properties` (never `$ref`, `oneOf`, or
 * an array `items`), which is the whole shape this engine's own element
 * config schemas use; a response schema reached through an unresolved `$ref`
 * degrades gracefully to the property's raw key rather than a title, and a
 * constraint outside the set above, or a description this cannot match,
 * falls back to valijson's own text rather than showing nothing.
 */
std::string humanize_schema_error (const nlohmann::json& schema,
const std::string& error_description,
const std::string& error_json_pointer);

} // namespace vayu::core
