/**
 * Copyright (c) 2026 Atharva Kusumbia
 *
 * This source code is licensed under the Apache 2.0 license found in the
 * LICENSE file in the "app" directory of this source tree.
 */

import { useEffect } from "react";
import Shell from "./components/layout/Shell";
import TitleBar from "./components/layout/TitleBar";
import UpdateBanner from "./components/shared/UpdateBanner";
import RecoveryBanner from "./components/shared/RecoveryBanner";
import Toaster from "./components/shared/Toaster";
import KeepAwakePrompt from "./components/shared/KeepAwakePrompt";
import {
	useConfigQuery,
	useHealthQuery,
	usePrefetchCollectionsAndRequests,
	usePrefetchRuns,
} from "./queries";
import { useElectronTheme } from "./hooks/useElectronTheme";
import { useActiveEnvironmentRestore } from "./hooks/useActiveEnvironmentRestore";
import { useActiveEnvironmentGuard } from "./hooks/useActiveEnvironmentGuard";
import { useAppearance } from "./hooks/useAppearance";
import { useScriptCompletionProvider } from "./hooks/useScriptCompletionProvider";
import { useVariableCompletionProvider } from "./hooks/useVariableCompletionProvider";
import { useScriptVariableCompletionProvider } from "./hooks/useScriptVariableCompletionProvider";
import { useScriptTypeDefinitions } from "./hooks/useScriptTypeDefinitions";
import { useMenuActions } from "./hooks/useMenuActions";
import { useMcpDataInvalidation } from "./hooks/useMcpDataInvalidation";
import { useHostSleepRecorder } from "./hooks/useHostSleepRecorder";
import { useSaveStore } from "./stores/save-store";

function App() {
	// Sync theme with OS/Electron settings
	useElectronTheme();

	// Apply UI font + interface scale preferences
	useAppearance();

	// Initialize health check with automatic polling
	useHealthQuery();

	// Drop a persisted environment id whose environment the engine no longer has
	// - it would otherwise keep riding on every composed payload.
	useActiveEnvironmentGuard();

	// Then restore the environment the engine has marked active - the selection
	// is stored engine-side, so it survives a restart and a reinstall. Ordered
	// after the guard deliberately: the guard answers "does this id still
	// exist", this answers "which id does the engine hold", and a dangling id
	// should be dropped rather than pushed back at the engine as a selection.
	useActiveEnvironmentRestore();

	// Prefetch collections and all their requests (TanStack handles caching automatically)
	usePrefetchCollectionsAndRequests();
	// Warm the runs list once, rather than observing it from here: History,
	// Welcome and the palette poll it themselves while they are mounted, and a
	// root observer polled it for the app's whole life with nobody reading the
	// result (#1150).
	usePrefetchRuns();

	// Keep engine config warm - proxied call timeouts derive from its
	// defaultTimeout setting (see services/api.ts proxiedRequestTimeoutMs)
	useConfigQuery();

	// Fetch pm.* completions and register them with Monaco's JavaScript language
	useScriptCompletionProvider();
	// `{{variable}}` completion in the body editors. Global per language, so one
	// registration covers every editor instance - same as the line above.
	useVariableCompletionProvider();
	// What a `{{variable}}` resolves to is answered by the app's own tooltip,
	// per editor, in `EditorVariableTokens` - not by a hover provider here
	// (issue #1320).
	// Variable names inside `pm.environment.get("…")` and its siblings - the
	// script editors' equivalent of the line above, since a script names
	// variables through the accessors rather than through braces.
	useScriptVariableCompletionProvider();
	// The same surface as a `.d.ts`, generated by the engine from the same
	// table. Completions give a dropdown; these give hover documentation and
	// signature help, which a suggestion list cannot.
	useScriptTypeDefinitions();

	// Bridge native menu items (Preferences…/Settings) to in-app navigation
	useMenuActions();

	// An agent writing over MCP mutates the engine from the main process, which
	// no query can see. This is the channel that tells the cache to refetch.
	useMcpDataInvalidation();

	// The app asks the OS not to sleep under a run, but a closed lid overrides
	// that. Mounted here rather than on the dashboard: the suspend arrives with
	// no warning and the dashboard may not be the open tab, while the run it
	// interrupts streams from a service that outlives every view (#1357).
	useHostSleepRecorder();

	// Register Electron before-quit handler to flush pending saves
	useEffect(() => {
		if (!window.electronAPI?.onBeforeQuit) return;
		return window.electronAPI.onBeforeQuit(async () => {
			await useSaveStore.getState().flushAll();
		});
	}, []);

	return (
		<div className="flex flex-col h-full">
			<TitleBar />
			{/* Above the update banner: one says a newer version exists, the
			    other says the user's data is gone. */}
			<RecoveryBanner />
			<UpdateBanner />
			<div className="flex-1 overflow-hidden">
				<Shell />
			</div>
			<Toaster />
			{/* Asks, once, about a run long enough for the machine to sleep under
			    it - and only while the standing preference is off (#1357). */}
			<KeepAwakePrompt />
		</div>
	);
}

export default App;
