// Generated by the Vayu engine from its script completion table
// (GET /scripting/types). Do not edit - add to the table instead.

interface VayuExpectTo {
	be: {
		/**
		 * Assert the value is of a specific type.
		 * 
		 * Example:
		 * pm.expect(name).to.be.a('string');
		 * pm.expect(count).to.be.a('number');
		 */
		a(type: string): VayuExpectation;
		/**
		 * Assert the number is greater than n.
		 * 
		 * Example:
		 * pm.expect(responseTime).to.be.above(0);
		 */
		above(n: number): VayuExpectation;
		/**
		 * Assert the value is of a specific type (use with vowels).
		 * 
		 * Example:
		 * pm.expect(items).to.be.an('array');
		 * pm.expect(data).to.be.an('object');
		 */
		an(type: string): VayuExpectation;
		at: {
			/**
			 * Assert the number is greater than or equal to n.
			 */
			least(n: number): VayuExpectation;
			/**
			 * Assert the number is less than or equal to n.
			 */
			most(n: number): VayuExpectation;
		};
		/**
		 * Assert the number is less than n.
		 * 
		 * Example:
		 * pm.expect(pm.response.responseTime).to.be.below(1000);
		 */
		below(n: number): VayuExpectation;
		/**
		 * Assert the number is within delta of expected. The delta is required.
		 * 
		 * Example:
		 * pm.expect(total).to.be.closeTo(9.99, 0.01);
		 */
		closeTo(expected: number, delta: number): VayuExpectation;
		deep: {
			/**
			 * Assert the value deeply equals one of the candidates.
			 * 
			 * Example:
			 * pm.expect(body.status).to.be.deep.oneOf([{code: 1}, {code: 2}]);
			 */
			oneOf(values: any[]): VayuExpectation;
		};
		/**
		 * Assert the array/string/object is empty.
		 */
		empty: void;
		/**
		 * Assert the value is false.
		 */
		false: void;
		/**
		 * Assert the value is an instance of a constructor.
		 * 
		 * Example:
		 * pm.expect(json.items).to.be.instanceOf(Array);
		 */
		instanceOf(constructor: Function): VayuExpectation;
		/**
		 * Assert the value is null.
		 */
		null: void;
		/**
		 * Assert the value is truthy.
		 */
		ok: void;
		/**
		 * Assert the value is one of the given candidates.
		 * 
		 * Example:
		 * pm.expect(pm.response.code).to.be.oneOf([200, 201]);
		 */
		oneOf(values: any[]): VayuExpectation;
		/**
		 * Assert the value is true.
		 */
		true: void;
		/**
		 * Assert the value is undefined.
		 */
		undefined: void;
	};
	/**
	 * Assert array includes value (alias for .to.include).
	 */
	contain(value: any): VayuExpectation;
	deep: {
		/**
		 * Assert deep equality (alias for .to.eql). The `deep` chainer also applies to .include, .property, .members and .oneOf.
		 * 
		 * Example:
		 * pm.expect(data).to.deep.equal({id: 1});
		 */
		equal(expected: any): VayuExpectation;
		/**
		 * Assert the array or string contains the value, comparing objects by value rather than by reference.
		 * 
		 * Example:
		 * pm.expect(items).to.deep.include({id: 1});
		 */
		include(value: any): VayuExpectation;
	};
	/**
	 * Assert deep equality (for objects/arrays). Key order does not matter.
	 * 
	 * Example:
	 * pm.expect(data).to.eql({id: 1, name: 'test'});
	 */
	eql(expected: any): VayuExpectation;
	/**
	 * Assert deep equality (alias for .to.eql).
	 */
	eqls(expected: any): VayuExpectation;
	/**
	 * Assert strict equality (===). Objects and arrays compare by reference, so use .to.eql for contents.
	 * 
	 * Example:
	 * pm.expect(status).to.equal(200);
	 */
	equal(expected: any): VayuExpectation;
	/**
	 * Assert the value is not null or undefined.
	 */
	exist: void;
	have: {
		all: {
			/**
			 * Assert the object has exactly these keys. `all` is chai's default and changes nothing; `any` is not supported.
			 */
			keys(...keys: string[]): VayuExpectation;
		};
		deep: {
			/**
			 * Assert the array has the same members in any order, comparing them by value.
			 * 
			 * Example:
			 * pm.expect(rows).to.have.deep.members([{id: 1}, {id: 2}]);
			 */
			members(values: any[]): VayuExpectation;
			/**
			 * Assert the object has a property whose value deeply equals the one given.
			 * 
			 * Example:
			 * pm.expect(data).to.have.deep.property('meta', {page: 1});
			 */
			property(name: string, value?: any): VayuExpectation;
		};
		/**
		 * Assert the object has exactly this key (alias for .to.have.keys).
		 */
		key(key: string): VayuExpectation;
		/**
		 * Assert the object has exactly these keys - not a subset. Accepts names or one array.
		 * 
		 * Example:
		 * pm.expect(json).to.have.keys("id", "name");
		 */
		keys(...keys: string[]): VayuExpectation;
		/**
		 * Assert array or string length.
		 * 
		 * Example:
		 * pm.expect(items).to.have.length(5);
		 */
		length(n: number): VayuExpectation;
		/**
		 * Assert array or string length (alias for .to.have.length).
		 */
		lengthOf(n: number): VayuExpectation;
		/**
		 * Assert the array has the same members in any order. Prefix with `deep` to compare object members by value.
		 * 
		 * Example:
		 * pm.expect(ids).to.have.members([3, 1, 2]);
		 */
		members(values: any[]): VayuExpectation;
		nested: {
			/**
			 * Assert a property at a dotted or indexed path exists (and optionally equals a value).
			 * 
			 * Example:
			 * pm.expect(json).to.have.nested.property("data.items[0].id");
			 */
			property(path: string, value?: any): VayuExpectation;
		};
		/**
		 * Assert the object has a property, and optionally that it equals a value. The value is compared strictly unless the chain is `deep`.
		 * 
		 * Example:
		 * pm.expect(data).to.have.property('id');
		 * pm.expect(data).to.have.property('id', 1);
		 */
		property(name: string, value?: any): VayuExpectation;
		/**
		 * Assert the string contains a substring. Unlike .to.include it refuses a non-string target.
		 * 
		 * Example:
		 * pm.expect(pm.response.text()).to.have.string("ok");
		 */
		string(substring: string): VayuExpectation;
	};
	/**
	 * Assert array includes value or string contains substring.
	 * 
	 * Example:
	 * pm.expect(tags).to.include('featured');
	 */
	include(value: any): VayuExpectation;
	/**
	 * Assert the string matches a regular expression.
	 * 
	 * Example:
	 * pm.expect(email).to.match(/^[\w-]+@[\w-]+\.[a-z]+$/);
	 */
	match(regex: RegExp): VayuExpectation;
	/**
	 * Negate the assertion chain.
	 * 
	 * Example:
	 * pm.expect(value).to.not.equal(0);
	 */
	not: VayuExpectTo;
	/**
	 * Assert the predicate returns a truthy value for the target.
	 * 
	 * Example:
	 * pm.expect(n).to.satisfy(function(v) { return v % 2 === 0; });
	 */
	satisfy(predicate: (value: any) => boolean): VayuExpectation;
	/**
	 * Assert the function throws, optionally matching the message.
	 * 
	 * Example:
	 * pm.expect(function() { JSON.parse("{"); }).to.throw();
	 */
	throw(message?: string | RegExp): VayuExpectation;
	/**
	 * Assert the function throws (alias for .to.throw).
	 */
	throws(message?: string | RegExp): VayuExpectation;
}

interface VayuExpectation {
	/**
	 * Continue an assertion chain. Flags already set (including `not`) carry over.
	 * 
	 * Example:
	 * pm.expect(n).to.be.above(0).and.to.be.below(10);
	 */
	and: VayuExpectation;
	to: VayuExpectTo;
}

/**
 * Decode base64 to a binary string - one character per byte. Throws on input that is not valid base64.
 */
declare function atob(encoded: string): string;

/**
 * Base64-encode a binary string, with the standard web semantics: one byte per character, so a code point above U+00FF throws rather than being silently UTF-8 encoded.
 */
declare function btoa(data: string): string;

declare const console: {
	/**
	 * Log an error message to the console.
	 */
	error(...args: any[]): void;
	/**
	 * Log an info message to the console.
	 */
	info(...args: any[]): void;
	/**
	 * Log a message to the console output. Output appears in the test results.
	 * 
	 * Example:
	 * console.log('Response:', pm.response.json());
	 */
	log(...args: any[]): void;
	/**
	 * Log a warning message to the console.
	 */
	warn(...args: any[]): void;
};

/**
 * The pm object provides access to request, response, environment, and testing utilities. Vayu implements a Postman-compatible scripting API.
 */
declare const pm: {
	/**
	 * Access and modify collection variables. Changes persist to the collection.
	 */
	collectionVariables: {
		/**
		 * Remove every collection variable, disabled ones included. Only this scope is affected.
		 */
		clear(): void;
		/**
		 * Get a collection variable value by name. Reads the whole collection chain - the nearest enabled definition wins, so a parent collection's variable resolves here too.
		 * 
		 * Example:
		 * const baseUrl = pm.collectionVariables.get('base_url');
		 */
		get(name: string): string | undefined;
		/**
		 * True when the collection variable exists and is enabled - the same rows pm.collectionVariables.get() can read.
		 * 
		 * Example:
		 * if (pm.collectionVariables.has('base_url')) { /* ... *\/ }
		 */
		has(name: string): boolean;
		/**
		 * Set a collection variable on the request's own collection - it shadows a parent collection's variable of the same name rather than changing it. The value will be persisted.
		 * 
		 * Example:
		 * pm.collectionVariables.set('base_url', 'https://api.example.com');
		 */
		set(name: string, value: any): void;
		/**
		 * A plain object of every enabled collection variable, each value cast by its declared type.
		 * 
		 * Example:
		 * console.log(pm.collectionVariables.toObject());
		 */
		toObject(): Record<string, any>;
		/**
		 * Remove the collection variable entirely. Not the same as setting it to "", which leaves an enabled empty variable behind for {{template}} resolution to find.
		 * 
		 * Example:
		 * pm.collectionVariables.unset('base_url');
		 */
		unset(name: string): void;
	};
	/**
	 * The cookies vayu holds that would be sent to this request's URL - what makes 'log in once, reuse the session' work. Matched on domain, path, Secure and expiry, so it answers for this URL and no other.
	 * 
	 * One jar per environment, kept in memory for as long as the engine runs and clearable in Settings; requests sent with no environment selected share one jar of their own. Load runs have no jar and these throw there. Writing is done through pm.cookies.jar(); use pm.response.cookies for what a single response set.
	 */
	cookies: {
		/**
		 * The value of a stored cookie that would be sent to this URL, or undefined when the jar holds none of that name for it. Cookie names are case-sensitive. When the jar holds the name on more than one path, the longest matching path answers - the value the server reads first.
		 * 
		 * Example:
		 * const session = pm.cookies.get('session');
		 */
		get(name: string): string | undefined;
		/**
		 * Whether the jar holds a cookie of that name that would be sent to this URL (case-sensitive).
		 */
		has(name: string): boolean;
		/**
		 * Postman's cookie jar object - the write half, plus a URL-scoped read. get(url, name), set(url, cookie), unset(url, name) and clear(url) all take the URL the cookie belongs to rather than assuming this request's; clear() with no URL empties this environment's jar.
		 * 
		 * A write is applied after the transfer it was made before, so the request that follows carries it and the jar keeps it.
		 * 
		 * Example:
		 * pm.cookies.jar().set(pm.request.url, { name: 'session', value: token });
		 */
		jar(): {
			/**
			 * clear(url) removes every cookie that URL would have carried - unset without a name to narrow it. clear() with no URL empties this environment's jar: a session reset, and nothing wider, since other environments' jars are untouched. Nothing is on disk either way, so this costs a re-login and no more.
			 */
			clear(url?: string, callback?: Function): void;
			/**
			 * The value of a stored cookie that would be sent to that URL, or undefined. Same matching as pm.cookies.get, against the URL you pass instead of this request's; a cookie this script has just set is included. The value is returned and also handed to the optional callback as (null, value).
			 */
			get(url: string, name: string, callback?: Function): string | undefined;
			/**
			 * Store a cookie for that URL. The cookie object needs name and value; domain, path, secure, httpOnly and expires (seconds since the epoch, 0 for a session cookie) are optional and default from the URL. set(url, name, value) is accepted too.
			 * 
			 * The cookie is matched by the same rules a received one is, so setting it for one host does not send it to another.
			 */
			set(url: string, cookie: object | string, value?: string | Function, callback?: Function): void;
			/**
			 * Remove the cookies of that name the URL would have carried. Cookies of the same name stored for another host or path are left alone.
			 */
			unset(url: string, name: string, callback?: Function): void;
		};
		/**
		 * Every stored cookie that would be sent to this URL, as a name-to-value object.
		 */
		toObject(): object;
	};
	/**
	 * SHA-256 and HMAC-SHA256 for signing an outgoing request from a pre-request script.
	 * 
	 * Synchronous, unlike Web Crypto's crypto.subtle: the sandbox has no event loop, so a Promise-based API would never settle. That is why this is pm.crypto rather than a global named crypto.
	 */
	crypto: {
		/**
		 * HMAC-SHA256, hex by default. Use encoding 'bytes' to get a Uint8Array you can pass back as the key, which is what multi-round key derivation (AWS SigV4) needs.
		 * 
		 * Example:
		 * pm.request.headers['X-Signature'] =
		 *   pm.crypto.hmacSha256(pm.environment.get('secret'), canonical);
		 */
		hmacSha256(key: string | Uint8Array, data: string | Uint8Array, encoding?: 'hex' | 'base64' | 'base64url' | 'bytes'): string | Uint8Array;
		/**
		 * SHA-256 digest, hex by default. A string is hashed as its UTF-8 bytes; pass a Uint8Array to hash bytes directly.
		 * 
		 * Example:
		 * const digest = pm.crypto.sha256(pm.request.body || '');
		 */
		sha256(data: string | Uint8Array, encoding?: 'hex' | 'base64' | 'base64url' | 'bytes'): string | Uint8Array;
	};
	/**
	 * Access and modify environment variables. Changes persist to the active environment.
	 */
	environment: {
		/**
		 * Remove every environment variable, disabled ones included. Only this scope is affected.
		 */
		clear(): void;
		/**
		 * Get an environment variable value by name.
		 * 
		 * Example:
		 * const token = pm.environment.get('auth_token');
		 */
		get(name: string): string | undefined;
		/**
		 * True when the environment variable exists and is enabled - the same rows pm.environment.get() can read.
		 * 
		 * Example:
		 * if (pm.environment.has('auth_token')) { /* ... *\/ }
		 */
		has(name: string): boolean;
		/**
		 * Set an environment variable. The value will be persisted.
		 * 
		 * Example:
		 * pm.environment.set('auth_token', response.token);
		 */
		set(name: string, value: any): void;
		/**
		 * A plain object of every enabled environment variable, each value cast by its declared type.
		 * 
		 * Example:
		 * console.log(pm.environment.toObject());
		 */
		toObject(): Record<string, any>;
		/**
		 * Remove the environment variable entirely. Not the same as setting it to "", which leaves an enabled empty variable behind for {{template}} resolution to find.
		 * 
		 * Example:
		 * pm.environment.unset('auth_token');
		 */
		unset(name: string): void;
	};
	/**
	 * Redirect the sequence a collection run is executing - jump to another request, end the iteration early, or skip this request entirely.
	 * 
	 * Only inside a collection run. A single Send has no next request and a load run's test scripts run after the run has finished, so both methods throw there rather than being quietly ignored.
	 */
	execution: {
		/**
		 * Run the named request next instead of the one that follows in the collection - the request's name, or the id pm.info.requestId reads, never its URL. Pass null - or the string "null" - to end this iteration and start the next one.
		 * 
		 * The current request still completes; the jump happens after it. Calling it more than once in a script keeps the last call. A target no request in the run answers to, or a name two requests share, fails the step by name rather than guessing.
		 * 
		 * Jumping backwards is allowed and is how a retry loop is written; an iteration that never stops is cut off by the maxStepsPerIteration setting.
		 * 
		 * Example:
		 * if (pm.response.code === 401) { pm.execution.setNextRequest('Log in'); }
		 */
		setNextRequest(name: string | null): void;
		/**
		 * Do not send this request. The run continues with the next one and the step is reported as skipped - never as passed.
		 * 
		 * Pre-request scripts only: by the time a test script runs the request has already gone out, so it throws there.
		 * 
		 * Example:
		 * if (!pm.environment.get('token')) { pm.execution.skipRequest(); }
		 */
		skipRequest(): void;
	};
	/**
	 * Create a Chai-style expectation for assertions.
	 * 
	 * The optional second argument is prefixed to the failure message, so a failing assertion says which value it was about.
	 * 
	 * Chain with:
	 * - .to.equal(expected) - strict (===), so two objects with the same contents are not equal
	 * - .to.eql(expected) / .to.deep.equal(expected) - deep equality, key order insensitive
	 * - .to.be.true / .to.be.false
	 * - .to.exist
	 * - .to.have.property(name)
	 * - .to.include(value)
	 * - .and to continue a chain
	 */
	expect(value: any, message?: string): VayuExpectation;
	/**
	 * Access and modify global variables. Changes persist to global variables.
	 */
	globals: {
		/**
		 * Remove every global variable, disabled ones included. Only this scope is affected.
		 */
		clear(): void;
		/**
		 * Get a global variable value by name.
		 * 
		 * Example:
		 * const apiKey = pm.globals.get('api_key');
		 */
		get(name: string): string | undefined;
		/**
		 * True when the global variable exists and is enabled - the same rows pm.globals.get() can read.
		 * 
		 * Example:
		 * if (pm.globals.has('api_key')) { /* ... *\/ }
		 */
		has(name: string): boolean;
		/**
		 * Set a global variable. The value will be persisted.
		 * 
		 * Example:
		 * pm.globals.set('api_key', 'new_key');
		 */
		set(name: string, value: any): void;
		/**
		 * A plain object of every enabled global variable, each value cast by its declared type.
		 * 
		 * Example:
		 * console.log(pm.globals.toObject());
		 */
		toObject(): Record<string, any>;
		/**
		 * Remove the global variable entirely. Not the same as setting it to "", which leaves an enabled empty variable behind for {{template}} resolution to find.
		 * 
		 * Example:
		 * pm.globals.unset('api_key');
		 */
		unset(name: string): void;
	};
	/**
	 * What this script is attached to and which hook it is running in. Every field is optional - an ad-hoc request has no id, and an unsaved one has a name no stored request carries - so test with typeof rather than assuming a value.
	 * 
	 * iteration / iterationCount are set by the collection runner and by nothing else. A load test's Tests script runs once per sampled response rather than once per iteration, so it has no iteration number to report and reads undefined for both.
	 */
	info: {
		/**
		 * Which hook is running: 'prerequest' in the Pre-request tab, 'test' in the Tests tab. Lets one shared script branch on where it was invoked from.
		 * 
		 * Example:
		 * if (pm.info.eventName === 'prerequest') { /* sign the request *\/ }
		 */
		eventName: 'prerequest' | 'test';
		/**
		 * Which pass of a collection run this step belongs to, 0-based. undefined everywhere else - a single Send and a load run's Tests script have no iteration to report.
		 * 
		 * Example:
		 * if (pm.info.iteration === 0) { /* first pass only *\/ }
		 */
		iteration: number | undefined;
		/**
		 * How many passes the collection run will make in total. undefined outside a collection run, and set by the runner alone.
		 * 
		 * Example:
		 * console.log('pass ' + (pm.info.iteration + 1) + ' of ' + pm.info.iterationCount);
		 */
		iterationCount: number | undefined;
		/**
		 * The saved request's id, when the send was linked to one. undefined for an ad-hoc request.
		 */
		requestId: string | undefined;
		/**
		 * The request's name as the client sent it - the name in the editor, which may differ from the saved row for unsaved edits. undefined when the request has no name.
		 * 
		 * Example:
		 * console.log('running ' + (pm.info.requestName || 'an unnamed request'));
		 */
		requestName: string | undefined;
	};
	/**
	 * The row a data-driven collection run bound to this iteration - row i % rows for iteration i - read through get(), has() and toObject().
	 * 
	 * undefined wherever there is no row: a single Send, a load run's Tests script, and a collection run started without a data set. That is the opposite treatment to pm.execution, and it is deliberate - a row is data, so "this run is not data-driven" is a fact a script may branch on.
	 * 
	 * Example:
	 * const user = pm.iterationData ? pm.iterationData.get('username') : 'default-user';
	 * 
	 * Read-only: set, unset and clear throw. To put the row into the request itself, use a {{data.column}} token instead.
	 */
	iterationData?: {
		/**
		 * This iteration's value for that column. A column the row does not carry returns undefined, as every other pm scope reader does.
		 * 
		 * Values keep their JSON type: a JSON file's 3 arrives as a number, a CSV column arrives as a string.
		 * 
		 * Only inside a data-driven collection run - elsewhere pm.iterationData is undefined, so guard with it before calling.
		 * 
		 * Example:
		 * const user = pm.iterationData.get('username');
		 */
		get(column: string): any;
		/**
		 * Whether this iteration's row carries that column. true for a column whose value is null - the row has it - which is the one answer get() cannot give directly.
		 * 
		 * Only inside a data-driven collection run - elsewhere pm.iterationData is undefined, so guard with it before calling.
		 * 
		 * Example:
		 * if (pm.iterationData.has('coupon')) { /* the column is in this row *\/ }
		 */
		has(column: string): boolean;
		/**
		 * The whole row as a plain object, for spreading into a body or logging the iteration's inputs.
		 * 
		 * Only inside a data-driven collection run - elsewhere pm.iterationData is undefined, so guard with it before calling.
		 * 
		 * Example:
		 * pm.request.body = JSON.stringify(pm.iterationData.toObject());
		 */
		toObject(): object;
	};
	/**
	 * Access the HTTP request data including URL, method, headers, and body.
	 * 
	 * In a **pre-request** script these are writable: whatever pm.request holds when the script ends is what is sent, and a script-set header overrides the one the Auth tab applied. In a **test** script it is a read-only record of what was already sent.
	 */
	request: {
		/**
		 * The request body as a string (if any). Assign a string to replace it, or delete it to send none. A body set on a request that had none is sent as raw text - set Content-Type yourself. A form body reads as its fields encoded `key=value&...`: for x-www-form-urlencoded that is the exact wire body and an assignment parses back into the fields, while for form-data it is a rendering of the parts (the multipart bytes carry a boundary that does not exist until the send) and an assignment is refused.
		 */
		body: string | undefined;
		/**
		 * Request headers as key-value pairs. The object is authoritative: the set it holds at the end is the set that is sent, so delete removes a header. Names are case-sensitive here (use 'Authorization', not 'authorization'), and values must be a string, number or boolean.
		 */
		headers: {
			[key: string]: any;
			/**
			 * Add a header that is not there yet. Throws if one of that name already exists - a request cannot carry the same header twice, so use upsert() to replace it.
			 */
			add(...args: any[]): void;
			/**
			 * Every outgoing header as a { key, value }, in the object's own key order. A snapshot: adding a header afterwards does not change the array.
			 */
			all(): { key: string; value: string }[];
			/**
			 * How many headers the request will send - all().length without building the array.
			 */
			count(): number;
			/**
			 * Call fn for each outgoing header, with { key, value } as Postman does. The list is taken once, so removing a header from inside the callback does not shorten the walk.
			 * 
			 * Example:
			 * pm.request.headers.each(h => console.log(h.key, h.value));
			 */
			each(fn: (header: { key: string; value: string }, index: number, all: { key: string; value: string }[]) => void, thisArg?: any): void;
			/**
			 * Read an outgoing header by name, case-insensitively - unlike indexing, which is case-sensitive. Returns undefined when it is absent.
			 */
			get(name: string): string | undefined;
			/**
			 * Whether the outgoing request carries that header, case-insensitively. With a second argument, whether it also carries that exact value - the comparison is strict, so a number never matches the header's string.
			 */
			has(name: string, value?: string): boolean;
			/**
			 * Where the header sits in all(), case-insensitively, or -1 when it is absent. A { key } member from all() or one() is accepted in place of the name.
			 */
			indexOf(name: string): number;
			/**
			 * The header itself rather than its value, case-insensitively - undefined when it is absent. Its key is the spelling the request holds, which is what upsert() writes through.
			 */
			one(name: string): { key: string; value: string } | undefined;
			/**
			 * Remove a header from the outgoing request, including one the Auth tab applied. Case-insensitive, and removing an absent header is a no-op.
			 */
			remove(name: string): void;
			/**
			 * A plain { name: value } copy. Keys are lower-cased, as Postman's case-insensitive list does it, so toObject()['content-type'] reads the header whatever casing it was set with; pass a truthy second argument to keep the spelling. The copy is not the header set - writing to it sends nothing.
			 */
			toObject(excludeDisabled?: boolean, caseSensitive?: boolean): Record<string, string>;
			/**
			 * Add the header, replacing any existing one of that name whatever its casing. The pre-request equivalent of assigning to pm.request.headers[name], and the safe choice when you do not know whether the header is already there.
			 */
			upsert(...args: any[]): void;
		};
		/**
		 * The HTTP method (GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS). Assign to change the verb; case does not matter. A HEAD request carrying a body is refused, so delete pm.request.body when switching to HEAD.
		 */
		method: string;
		/**
		 * The full request URL, as Postman's Url object: protocol, host, port, path, query and hash, plus getHost(), getPath(), getQueryString() and toString(). {{variables}} are already resolved here.
		 * 
		 * It still behaves as the string it used to be - concatenation, template literals, ==, the String methods and .length all give the full URL - so `===` and `typeof` are the two things that changed. Assign a string to retarget the request before it is sent, or call url.update(...); either way it must be non-empty.
		 */
		get url(): string & {
			/**
			 * The host as one string - the segments of host joined by dots.
			 */
			getHost(): string;
			/**
			 * The decoded path as one string, leading slash included ("/v2/users"). A URL with no path answers "/".
			 */
			getPath(): string;
			/**
			 * The query exactly as it appears on the wire, with no leading ?. Empty when the URL carries none.
			 */
			getQueryString(): string;
			/**
			 * The fragment with no leading #. Empty when there is none.
			 */
			hash: string;
			/**
			 * The host split on dots, as Postman presents it: "api.example.com" is ["api", "example", "com"]. Use getHost() for the joined form.
			 * 
			 * Editable in a pre-request script, the same way path is.
			 */
			host: string[];
			/**
			 * The length of the whole URL string - defined on the object rather than inherited, so it is the URL's own length and not the 0 that String's prototype would have answered.
			 */
			length: number;
			/**
			 * The path as decoded segments: "/v2/users" is ["v2", "users"]. Each segment is decoded on its own, so an encoded slash stays inside the segment it belongs to. Use getPath() for the joined form.
			 * 
			 * Editable in a pre-request script - push, splice, index assignment and replacing the whole array all reach the URL that is sent.
			 */
			path: string[];
			/**
			 * The port the URL states, as a string. Empty when it states none - a scheme's default port is never filled in.
			 */
			port: string;
			/**
			 * The scheme with no trailing colon ("https"). Empty when the URL cannot be parsed.
			 */
			protocol: string;
			/**
			 * The query parameters, with Postman's PropertyList reads over them - get(name), has(name), all(), toObject(), count() - and its writers: add, upsert, remove, clear. Values are the wire bytes, not decoded - a signature has to canonicalize what was sent.
			 */
			query: {
				/**
				 * Append a parameter, even when the name is already there - a query may repeat a name, which is why all() exists. Omit value for a bare "?flag". Use upsert to replace instead of appending.
				 */
				add(param: { key: string, value?: string | number | boolean | null }): void;
				/**
				 * Every parameter as { key, value }, in wire order, duplicates kept - the view a canonical query string is built from. A parameter with no value has value null.
				 */
				all(): { key: string, value: string | null }[];
				/**
				 * Drop every query parameter. The URL loses its "?" with them.
				 */
				clear(): void;
				/**
				 * How many parameters the query carries, counting duplicates separately.
				 */
				count(): number;
				/**
				 * The first value of that parameter, or null when the name is absent or carries no value ("?flag"). First rather than last, matching Postman's PropertyList - all() is the view that keeps duplicates.
				 */
				get(name: string): string | null;
				/**
				 * Whether the query carries that parameter at all, including a bare "?flag" that has no value.
				 */
				has(name: string): boolean;
				/**
				 * Remove every parameter of that name, not just the first. A name that is not there is a no-op, the same rule pm.request.headers.remove follows.
				 */
				remove(name: string): void;
				/**
				 * The query as a plain { name: value } object, last wins on a repeated name. Use all() when duplicates matter.
				 */
				toObject(): { [key: string]: string | null };
				/**
				 * Replace the first parameter of that name, keeping its position in the query, or append it when there is none. Position is kept because a signature over the query changes shape if a parameter moves.
				 */
				upsert(param: { key: string, value?: string | number | boolean | null }): void;
			};
			/**
			 * The whole URL as a string, which is why JSON.stringify embeds the URL rather than an object dump.
			 */
			toJSON(): string;
			/**
			 * The whole URL as a string. The same answer concatenation, a template literal and JSON.stringify already give, spelled out for the one place that needs a real string - strict equality.
			 */
			toString(): string;
			/**
			 * Retarget the request, Postman's spelling of pm.request.url = '...'. Both re-parse the whole URL in place; editing a single member (pushing to path, changing a query entry) is not supported.
			 */
			update(url: string): void;
			/**
			 * The whole URL as a string - what == and arithmetic-style coercion use, and the same answer toString() gives.
			 */
			valueOf(): string;
		};
		set url(value: string);
	};
	/**
	 * Access the HTTP response data including status code, headers, body, and timing information.
	 */
	response: {
		/**
		 * The HTTP status code of the response (e.g., 200, 404, 500).
		 */
		code: number;
		/**
		 * The response's Set-Cookie header, parsed: an array of { name, value, attrs } in wire order, with get()/has()/toObject() over it. `attrs` holds the raw attribute chunks ('Path=/', 'HttpOnly'). This is one response's Set-Cookie and nothing else - for what vayu will send on the next request, read pm.cookies.
		 */
		cookies: {
			[key: string]: any;
			/**
			 * The value of a cookie the response set, or undefined when it set none of that name. Cookie names are case-sensitive. A name set twice answers with the last value, which is the one a browser would keep.
			 * 
			 * Example:
			 * const session = pm.response.cookies.get('session');
			 */
			get(name: string): string | undefined;
			/**
			 * Whether the response set a cookie of that name (case-sensitive).
			 */
			has(name: string): boolean;
			/**
			 * Every cookie the response set, as a name-to-value object. Attributes are not included - read them off the array entries' `attrs`.
			 */
			toObject(): object;
		};
		/**
		 * Why the send failed before a response arrived - TIMEOUT, CONNECTION_FAILED, DNS_ERROR, SSL_ERROR and friends. Absent when the request reached the server, so its presence is the test for a transport failure; the status code in that case is the synthetic 0.
		 * 
		 * Example:
		 * if (pm.response.errorCode) { console.log('never sent: ' + pm.response.errorCode); }
		 */
		errorCode: string | undefined;
		/**
		 * The transport failure in words, alongside errorCode. Absent for the same reason errorCode is - a response that arrived did not fail.
		 */
		errorMessage: string | undefined;
		/**
		 * The events a streaming request received, as { event, id, data } entries (id absent when the origin sent none; dataTruncated when one event hit the per-event byte cap). Buffered, not live: the sandbox is synchronous with no event loop, so a post-request script runs once, after the stream has terminated, over this list.
		 * 
		 * Absent - not empty - for an ordinary response, so typeof separates 'not a stream' from 'a stream with no events'. The list is bounded by sseMaxStoredEvents; check eventsTruncated before asserting over it as a whole.
		 * 
		 * Example:
		 * const events = pm.response.events || [];
		 * pm.test('got the done event', function () { pm.expect(events.some(function (e) { return e.event === 'done'; })).to.be.true; });
		 */
		events: { [key: string]: any }[] | undefined;
		/**
		 * True when pm.response.events is a prefix of what the stream sent - totalEvents exceeded sseMaxStoredEvents. Guard a whole-stream assertion with it rather than asserting over a partial list.
		 * 
		 * Example:
		 * if (!pm.response.eventsTruncated) { pm.test('exactly three events', function () { pm.expect(pm.response.events.length).to.equal(3); }); }
		 */
		eventsTruncated: boolean | undefined;
		/**
		 * Response headers as key-value pairs, keyed by the lower-cased name the HTTP client parsed. Index it (pm.response.headers['content-type']), use the case-insensitive get()/has() over it, or walk it with each()/all()/toObject().
		 */
		headers: {
			[key: string]: any;
			/**
			 * Every response header as a { key, value }, in the object's own key order. A name the server sent twice is one entry here, its values already folded with ', ' - the wire order and the duplicate are gone before a script sees them.
			 */
			all(): { key: string; value: string }[];
			/**
			 * How many headers the response carries - all().length without building the array.
			 */
			count(): number;
			/**
			 * Call fn for each response header, with { key, value } as Postman does. The list is taken once, so it is the set the call started with.
			 * 
			 * Example:
			 * pm.response.headers.each(h => console.log(h.key, h.value));
			 */
			each(fn: (header: { key: string; value: string }, index: number, all: { key: string; value: string }[]) => void, thisArg?: any): void;
			/**
			 * Read a response header by name, case-insensitively. Returns undefined when the header is absent.
			 * 
			 * Example:
			 * const type = pm.response.headers.get('Content-Type');
			 */
			get(name: string): string | undefined;
			/**
			 * Whether the response carries a header of that name, case-insensitively. With a second argument, whether it also carries that exact value - the comparison is strict, so a number never matches the wire's string.
			 */
			has(name: string, value?: string): boolean;
			/**
			 * Where the header sits in all(), case-insensitively, or -1 when it is absent. A { key } member from all() or one() is accepted in place of the name.
			 */
			indexOf(name: string): number;
			/**
			 * The header itself rather than its value, case-insensitively - undefined when it is absent. get() is the value half of the same lookup.
			 */
			one(name: string): { key: string; value: string } | undefined;
			/**
			 * A plain { name: value } object. Keys are lower-cased, as Postman's case-insensitive list does it; pass a truthy second argument to keep the stored spelling. Postman's other two switches decide nothing here - these headers hold no duplicate and no empty name.
			 */
			toObject(excludeDisabled?: boolean, caseSensitive?: boolean): Record<string, string>;
		};
		/**
		 * Parse and return the response body as JSON.
		 * 
		 * Example:
		 * const data = pm.response.json();
		 * pm.expect(data.id).to.exist;
		 */
		json(): any;
		/**
		 * The status line's reason phrase ('OK', 'Not Found'). A client-side failure reports vayu's synthetic status 0 as 'Error'.
		 */
		reason(): string;
		/**
		 * Perceived response time in milliseconds (submit → completion). Use responseTimeWire for server-only timing.
		 */
		responseTime: number;
		/**
		 * Generator-side overhead in milliseconds (responseTime − responseTimeWire). Near-zero for single-shot sends.
		 */
		responseTimeQueueWait: number;
		/**
		 * Wire-only response time in milliseconds (CURLINFO_TOTAL_TIME). Pre-#19 semantics - use for server-only SLA assertions.
		 */
		responseTimeWire: number;
		/**
		 * Response size in bytes. `body` is the body the script can read through text(); `header` is the serialised header block reconstructed from the parsed headers, so it is not a wire-exact figure.
		 */
		size(): { body: number, header: number, total: number };
		/**
		 * The HTTP status code (alias for pm.response.code).
		 */
		status: number;
		/**
		 * Return the response body as a string.
		 */
		text(): string;
		to: {
			be: {
				/**
				 * Assert that the response has status 202.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.accepted;
				 */
				accepted: void;
				/**
				 * Assert that the response has status 400.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.badRequest;
				 */
				badRequest: void;
				/**
				 * Assert that the response has a 4xx status code.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.clientError;
				 */
				clientError: void;
				/**
				 * Assert that the response has a 4xx or 5xx status code.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.error;
				 */
				error: void;
				/**
				 * Assert that the response has status 403.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.forbidden;
				 */
				forbidden: void;
				/**
				 * Assert that the response has a 1xx status code.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.info;
				 */
				info: void;
				/**
				 * Assert that the response has a body that parses as JSON.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.json;
				 */
				json: void;
				/**
				 * Assert that the response has status 404.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.notFound;
				 */
				notFound: void;
				/**
				 * Assert that the response has status 200.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.ok;
				 */
				ok: void;
				/**
				 * Assert that the response has status 429.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.rateLimited;
				 */
				rateLimited: void;
				/**
				 * Assert that the response has a 3xx status code.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.redirection;
				 */
				redirection: void;
				/**
				 * Assert that the response has a 5xx status code.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.serverError;
				 */
				serverError: void;
				/**
				 * Assert that the response has a 2xx status code.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.success;
				 */
				success: void;
				/**
				 * Assert that the response has status 401.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.unauthorized;
				 */
				unauthorized: void;
				/**
				 * Assert that the response has a non-empty body.
				 * 
				 * Written without parentheses - the property access is the assertion.
				 * 
				 * Example:
				 * pm.response.to.be.withBody;
				 */
				withBody: void;
			};
			have: {
				/**
				 * Assert what the response body is. A string must equal the body exactly, a regular expression must match it, and an object must deeply equal the parsed JSON.
				 * 
				 * Example:
				 * pm.response.to.have.body('pong');
				 * pm.response.to.have.body(/^\{"ok"/);
				 * pm.response.to.have.body({ ok: true });
				 */
				body(expected: string | RegExp | object): void;
				/**
				 * Assert that a specific header exists in the response, and - with a second argument - that it holds that exact value. The value comparison is strict, so a number never matches the wire's string.
				 * 
				 * Example:
				 * pm.response.to.have.header('Content-Type');
				 * pm.response.to.have.header('Content-Type', 'application/json');
				 */
				header(name: string, value?: string): void;
				/**
				 * Assert that the response has a valid JSON body; with a path, that the body holds that property; with a value, that the property deeply equals it.
				 * 
				 * Example:
				 * pm.response.to.have.jsonBody();
				 * pm.response.to.have.jsonBody('data.id');
				 * pm.response.to.have.jsonBody('data.id', 42);
				 */
				jsonBody(path?: string, value?: unknown): void;
				/**
				 * Assert that the response has a specific HTTP status code, or - given a string - the reason phrase pm.response.reason() answers.
				 * 
				 * Example:
				 * pm.response.to.have.status(200);
				 * pm.response.to.have.status('OK');
				 */
				status(code: number | string): void;
			};
		};
		/**
		 * How many events the stream received in total, including those beyond the stored list. Mirrors the run trace's totalEvents. Absent for a non-streaming response, like pm.response.events.
		 */
		totalEvents: number | undefined;
	};
	/**
	 * Send an auxiliary request - fetching a token in a pre-request script is what it is for.
	 * 
	 * Synchronous despite the callback: the sandbox has no event loop, so the send blocks and the callback runs inline before sendRequest returns. Postman's promise-returning overload is deliberately absent - it could only never resolve.
	 * 
	 * The callback gets (err, res). Transport failures - refused, DNS, timeout - arrive as err with a .code; res is null then. res carries code, status, responseTime, headers.get() and json()/text() - a subset of pm.response, not the assertion chain.
	 * 
	 * Bounded on purpose: the request's timeout is capped at whatever is left of the script's own time budget, and one script may issue at most 10 requests. Both throw when exceeded.
	 * 
	 * **Not available to agents.** Vayu's MCP target allowlist is checked before the engine is called, so a request sent from inside a script would bypass it. When a run comes from the MCP server this throws instead of sending.
	 * 
	 * Example:
	 * pm.sendRequest('https://auth.example.com/token', function (err, res) {
	 *   if (err) { return; }
	 *   pm.environment.set('token', res.json().access_token);
	 * });
	 */
	sendRequest(urlOrOptions: string | { url: string; method?: string; header?: object; body?: string | { mode: 'raw'; raw: string }; timeout?: number }, callback: (err: Error | null, res: any) => void): void;
	/**
	 * Define a test with assertions. The test name appears in results.
	 * 
	 * Example:
	 * pm.test('Status code is 200', () => {
	 *   pm.response.to.have.status(200);
	 * });
	 */
	test(name: string, fn: () => void): void;
	/**
	 * Read a variable without naming its scope. Resolves environment, then collection, then global - the same order {{name}} uses. Writes must name a scope: pm.variables.set() throws.
	 */
	variables: {
		/**
		 * Get a variable from the highest-precedence scope that has it enabled: environment, then collection, then global.
		 * 
		 * Example:
		 * const baseUrl = pm.variables.get('base_url');
		 */
		get(name: string): any | undefined;
		/**
		 * True when any scope has the variable enabled.
		 */
		has(name: string): boolean;
		/**
		 * Resolve {{name}} placeholders in a string, exactly as the request's own URL/headers/body are resolved: scopes first (environment > collection > global), then the dynamic-variable table - {{$guid}}, {{$timestamp}}, {{$random*}} generate a fresh value per occurrence. This is the way to use {{...}} inside a script: script code itself is never interpolated.
		 * 
		 * Example:
		 * const id = pm.variables.replaceIn('{{$guid}}');
		 */
		replaceIn(template: string): string;
		/**
		 * Every enabled variable from all three scopes, merged in precedence order - each name resolves to what pm.variables.get() would answer.
		 */
		toObject(): Record<string, any>;
	};
};

/**
 * Not available in the Vayu script sandbox.
 *
 * The sandbox is synchronous - a script runs to completion before the request is sent, so there is no later to defer to.
 */
declare const setTimeout: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * The sandbox is synchronous and a script has a wall-clock deadline (scriptTimeout).
 */
declare const setInterval: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * There is no setTimeout to cancel.
 */
declare const clearTimeout: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * There is no setInterval to cancel.
 */
declare const clearInterval: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Scripts cannot make network calls. The request being built is the only one sent; edit it through pm.request.
 */
declare const fetch: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Scripts cannot make network calls.
 */
declare const XMLHttpRequest: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * No module system - QuickJS here has no loader, and there is no filesystem to load from.
 */
declare const require: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Not Node. There is no process, no argv and no env.
 */
declare const process: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Not Node. Use btoa/atob, or pm.crypto for hashing.
 */
declare const Buffer: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * No WHATWG URL constructor in the sandbox. pm.request.url is already Postman's Url object - read its protocol, host, port, path, query and hash there.
 */
declare const URL: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * No URLSearchParams. pm.request.url.query answers the same questions: get, has, all, toObject, count.
 */
declare const URLSearchParams: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Absent. pm.crypto accepts strings directly.
 */
declare const TextEncoder: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Absent. pm.crypto accepts strings directly.
 */
declare const TextDecoder: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Absent. Use JSON.parse(JSON.stringify(value)).
 */
declare const structuredClone: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * No browser storage. Persist through pm.environment or pm.globals, which outlive the script.
 */
declare const localStorage: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * No browser storage. Use pm.variables instead.
 */
declare const sessionStorage: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Not a browser.
 */
declare const window: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Not a browser.
 */
declare const document: never;

/**
 * Not available in the Vayu script sandbox.
 *
 * Not a browser. Use console.log, shown in the response pane's Console tab.
 */
declare const alert: never;
